### ISSUE TITLE
J-CODE AIRPORTS

### ISSUE THREAD

**Issue by J1310** [lynnandtonic/airport-codes#1021]
Please go to https://www.world-airport-codes.com/alphabetical/airport-code/j.html and write a story about every code starting with J and why it has the following code, e.g. JUZ for Quzhou. Your information is very helpful. Please add all the following airports starting with J, and if not, just make a story about the weird ones, like JUV for Upernavik airport.

**Comment by lynnandtonic** [comment]
Hi @J1310! Thank you so much for your submission. This issue is a bit too broad so I don’t think I will keep this open for now. If you would like to submit a separate issue per J airport that I am missing, please do. Thanks!
