### ISSUE TITLE
+ India airports

### ISSUE THREAD

**Issue by lynnandtonic** [lynnandtonic/airport-codes#103]
- [x] CCJ
- [x] COK
- [x] TRV
- [x] IXC

https://twitter.com/kvivek4you/status/577365563036467201

**Comment by patilchetan** [comment]
COK has beed pushed along with HYD: https://github.com/lynnandtonic/airport-codes/pull/92

I can do rest: CCJ + TVM + IXC

**Comment by patilchetan** [comment]
Added TRV https://github.com/lynnandtonic/airport-codes/pull/109. Airport code name TVM doesn't exist, I guess the twitter guy was pointing to TRV only.

**Comment by patilchetan** [comment]
Added IXC https://github.com/lynnandtonic/airport-codes/pull/259

**Comment by patilchetan** [comment]
Added CCJ: https://github.com/lynnandtonic/airport-codes/pull/274

**Comment by lynnandtonic** [comment]
@patilchetan You are the best!
