### ISSUE TITLE
+ FNJ

### ISSUE THREAD

**Issue by Kevin-ter-Woort** [lynnandtonic/airport-codes#1038]
Pyongyang International Airport
https://en.wikipedia.org/wiki/Pyongyang_International_Airport

Photo
https://en.wikipedia.org/wiki/Pyongyang_International_Airport#/media/File:FNJ_Terminal_2.jpg

**Comment by lynnandtonic** [comment]
> Today I learned why Pyongyang Sunan International Airport has the IATA code FNJ. I've been curious about this airport code since I noticed it wasn't on airportcod.es, and set out on a hunt for information. I emailed several travel agencies which offer trips to Pyongyang. I recieved a strong answer from Simon Cockerell from the agency Koryo Tours. He tells me that the abbreviation FNJ comes from the Cyrillic transliteration of the city's name, Пхеньян, which in the Latin alphabet would be written Phen’jan. So the ‘F’ as a phonetic substitute for the ‘Ph’, and the NJ come from the N and J in "Phen'jan". Thus, the code is FNJ! I really love your airportcod.es site, IATA codes are another little thing that tickles my brain and I love learning their origin!

From Cyril Lintner
