### ISSUE TITLE
MMK

### ISSUE THREAD

**Issue by AlexRoki** [lynnandtonic/airport-codes#1070]
Murmansk international airport

**Comment by AlexRoki** [comment]
![image](https://user-images.githubusercontent.com/47427879/52430063-4c3f4300-2b16-11e9-9402-f1c6cbc9c311.png)

**Comment by AlexRoki** [comment]
![image](https://user-images.githubusercontent.com/47427879/52431222-db4d5a80-2b18-11e9-9631-c4082ee64486.png)

**Comment by lynnandtonic** [comment]
Thank you @AlexRoki!

Are those your photographs? Or could you link to where you got them? We need to be sure there aren’t any license issues.

**Comment by AlexRoki** [comment]
The first pic is from here http://airspot.ru/catalogue/item/murmansk-murmansk-airport-murmashi-ulmm-mmk-murmansk-murmanskthe second one is mentioned in the json file with the copyright 07.02.2019, 21:18, "Lynn Fisher" <notifications@github.com>:Thank you @AlexRoki!Are those your photographs? Or could you link to where you got them? We need to be sure there aren’t any license issues.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by lynnandtonic** [comment]
Link for second photo: https://en.wikipedia.org/wiki/Murmansk_Airport#/media/File:Murmansk_(MMK_-_ULMM)_AN1445818.jpg
