### ISSUE TITLE
Please add Zheng Zhou Xinzheng International Airport

### ISSUE THREAD

**Issue by halimaramli** [lynnandtonic/airport-codes#1092]
Hello, 
Please add Zheng Zhou Xinzheng International Airport. 
IATA code CGO, ICAO code ZHCC. 
Zhengzhou Xinzheng International Airport located in the capital of Henan province in China; serves as a main gateway for the province.
Thank you

**Comment by lynnandtonic** [comment]
@halimaramli It's up on the site now! Thank you! 🌈
