### ISSUE TITLE
+ DRS

### ISSUE THREAD

**Issue by claudiush** [lynnandtonic/airport-codes#1108]
Dresden Airport is the international airport in Dresden, the capital of the German Free State of Saxony. The airport code is created by ommitting the vowels: **DR**e**S**den

Photo: https://www.flickr.com/photos/weiwei/307131826

{
    "id": "drs",
    "name": "Dresden International",
    "city": "Dresden",
    "state": "Saxony",
    "country": "Germany",
    "description": "Dresden Airport is the international airport in Dresden, the capital of the German Free State of Saxony. The airport code is created by ommitting the vowels: *DR*e*S*den",
    "imageCredit": "",
    "imageCreditLink": ""
}

**Comment by lynnandtonic** [comment]
Thank you so much, @claudiush! https://airportcod.es/#airport/drs
