### ISSUE TITLE
+ BLL

### ISSUE THREAD

**Issue by Yanotecreo** [lynnandtonic/airport-codes#1139]
Billund Airport opened in 1964 in an old hangar with a single control tower and a 1660-metre asphalt runway.

Since then the airport has experienced remarkable growth that is associated with a general economic and cultural development in the region. The airport has continuously expanded from having only two domestic departures a day to sending its passengers to destinations all over the world with many departures each day. Today the name of our airport is Billund Airport and has a passenger terminal of 40,000 m2, which is designed to handle 3.5 million passengers a year.
![image](https://user-images.githubusercontent.com/61391966/75119518-d4da4400-5683-11ea-8836-840f8c2b328b.png)

**Comment by lynnandtonic** [comment]
Thank you! 🌈
