### ISSUE TITLE
Filtering out airports that are international

### ISSUE THREAD

**Issue by 1-geo** [lynnandtonic/airport-codes#1197]
I wanted to get international airport codes from a given city. Is there a way to do that a solution on here or somewhere else?

**Comment by 1-geo** [comment]
@lynnandtonic Hi thanks for responding, really cool project. I'm looking to filter out non international airports for a given city. From the json model, I do not see any fields that mark it as an international airport. 

Is it fair to assume that if the 'name' key on the json contains International, then only its International airport?

**Comment by lynnandtonic** [comment]
@1-geo Ahh, ok I get what you mean. Right now, no there isn’t anything in the JSON that specifies international vs. national. Most of them do say “International” in the name, but I can not say it is super consistent or that it will give you a true list.

**Comment by lynnandtonic** [comment]
Hi @1-geo! Just following up that I don’t plan on adding a definitive "international" label to airports. Sorry about that! I suspect there are some more comprehensive lists out there that do this though. Thanks again!
