### ISSUE TITLE
Unable to checkout working tree

### ISSUE THREAD

**Issue by ekfuhrmann** [lynnandtonic/airport-codes#1208]
When trying to clone the repo I run into the following error:

```cmd
Resolving deltas: 100% (16040/16040), done.
error: invalid path 'assets/images/card/prn.jpg'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

When executing `git restore --source=HEAD :/` I receive the following:

```cmd
error: invalid path 'assets/images/card/prn.jpg'
error: invalid path 'assets/images/large/prn.jpg'
error: invalid path 'assets/images/medium/prn.jpg'
error: invalid path 'assets/images/small/prn.jpg'
error: invalid path 'data/prn.json'
```

**Comment by lynnandtonic** [comment]
Hey @ekfuhrmann, I’ve seen this and am looking into it!

**Comment by lynnandtonic** [comment]
@ekfuhrmann Hey! I just renamed those images and pushed an update to `main`. Do you want to try and see if that fixes your issue?

Are you by chance on a Windows machine? It ultimately might be [this issue](https://stackoverflow.com/questions/61614004/cloning-succeded-but-checkout-failed-due-to-invalid-path-what-is-the-path-probl) where Windows machines can’t handle files named `prn`. I just learned about i!

**Comment by ekfuhrmann** [comment]
Thanks @lynnandtonic for looking into it. I am indeed on a windows machine so that most likely seems to be the culprit. I'm not longer getting errors for the images but it seems that the `data/prn.json` is still causing it to error.

```cmd
C:\dev\airport-codes>git restore --source=HEAD :/
error: invalid path 'data/prn.json'
```

I also had no clue about those file name conflicts on Windows, very interesting find!

**Comment by lynnandtonic** [comment]
@ekfuhrmann Oh duh, of course it would. 😆 Ok I might need to tap someone else in here. I’ll get back to you.

**Comment by lynnandtonic** [comment]
@ekfuhrmann Ok I think we got it sorted for real this time. Do you want to try again?

**Comment by ekfuhrmann** [comment]
We're golden, thank you so much for figuring it out and addressing the issue.

Big fan of all of your projects by the way!

**Comment by lynnandtonic** [comment]
Yay! Thank you!!
