### ISSUE TITLE
+ KSC

### ISSUE THREAD

**Issue by iKristy** [lynnandtonic/airport-codes#1228]
Suggesting to add Kosice International Airport, IATA code is "KSC".

Website: https://www.airportkosice.sk/en

Photo: https://en.wikipedia.org/wiki/Ko%C5%A1ice_International_Airport#/media/File:Kosice_International_Airport.jpg

**Comment by lynnandtonic** [comment]
@iKristy Thank youuuuuu! 🌈  https://airportcod.es/#airport/ksc
