### ISSUE TITLE
+ STM

### ISSUE THREAD

**Issue by lynnandtonic** [lynnandtonic/airport-codes#1238]
STM - SanTaréM

https://twitter.com/maguiar11/status/1516546840728162310

**Comment by bagewadi-akram** [comment]
Santarém–Maestro Wilson Fonseca Airport (IATA: STM, ICAO: SBSN) is the airport serving Santarém, Brazil. It is named after the composer Wilson Dias da Fonseca (1912–2002), who was born in Santarém.
