### ISSUE TITLE
+ UIO

### ISSUE THREAD

**Issue by ncrohn** [lynnandtonic/airport-codes#126]
Aeropuerto Internacional Mariscal Sucre Quito, Ecuador

**Comment by lynnandtonic** [comment]
http://en.wikipedia.org/wiki/Mariscal_Sucre_International_Airport

https://www.flickr.com/photos/aero_icarus/4309945757
https://www.flickr.com/photos/presidenciaecuador/8554411847
https://www.flickr.com/photos/presidenciaecuador/8489457599
