### ISSUE TITLE
searching for BWI on the website

### ISSUE THREAD

**Issue by sputtering** [lynnandtonic/airport-codes#1261]
Normally on https://airportcod.es/ you can search by the airport code. For some reason, this does not work with BWI. You can search by Washington or Baltimore, and it comes up. But for some reason, the airport code is not searchable. I tested a few others, and all of the others that I tested did come up when searching by their airport code.

**Comment by lynnandtonic** [comment]
@sputtering Could you try again? I am able to search with "bwi" and can’t reproduce your issue. Thanks!

This is what I’m seeing:
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/871315/193472718-c4cb42f3-7e55-4063-8094-10e8f87e27d0.png">

**Comment by sputtering** [comment]
It seems to be working for me now. That's weird. It must have been a glitch in the matrix. Thanks for checking it out!

**Comment by lynnandtonic** [comment]
Whew sounds good! Thanks @sputtering! 🙌
