### ISSUE TITLE
+ NOC, CFN, KIR

### ISSUE THREAD

**Issue by lynnandtonic** [lynnandtonic/airport-codes#1279]
From email:

NOC – Ireland West Airport Knock – Derives its code from the nearby village of Knock.

CFN – Donegal Airport – Derives its code from Carrickfinn, the area in which it is located.

I would also suggest KIR – Kerry Airport, but I am unclear on its origin.

**Comment by computerfan0** [comment]
Regarding KIR – I believe that the code is meant to represent **Ki**lla**r**ney, which is the closest major town to the airport. I was somewhat unsure about this as I believed Tralee to be closer, but Google Maps shows that it is actually 1-2km further away.

**Comment by lynnandtonic** [comment]
Thank you @computerfan0! 🏆
