### ISSUE TITLE
+ PUB, DRO, EGE, ASE, TEX, GUC

### ISSUE THREAD

**Issue by lynnandtonic** [lynnandtonic/airport-codes#1287]
From email:

Here are a few around me. I live in COS, which you have, but I don't think you have:

- [x] PUB - Pueblo https://en.wikipedia.org/wiki/Pueblo_Memorial_Airport
- [x] **DRO - Durango https://en.wikipedia.org/wiki/Durango%E2%80%93La_Plata_County_Airport**
- [x] **EGE - Vail / Eagle County https://en.wikipedia.org/wiki/Eagle_County_Regional_Airport**
- [x] ASE - Aspen https://en.wikipedia.org/wiki/Aspen/Pitkin_County_Airport
- [x] TEX - Telluride https://en.wikipedia.org/wiki/Telluride_Regional_Airport
- [x] GUC - Gunnison - Crested Butte https://en.wikipedia.org/wiki/Gunnison%E2%80%93Crested_Butte_Regional_Airport

The two in bold are the most popular. Durango because it's a regional hub and popular [southwest Colorado destination](http://www.corailroads.com/search/label/Durango%20and%20Silverton). Eagle County because it serves everywhere west of Denver but east of Utah, including Vail and Beaver Creek ski areas.

**Comment by computerfan0** [comment]
DRO, EGE, ASE and GUC are already present, leaving only PUB and TEX to be added.

**Comment by lynnandtonic** [comment]
Thank you @computerfan0! 💃
