### ISSUE TITLE
+ CUL 

### ISSUE THREAD

**Issue by kamikaze15** [lynnandtonic/airport-codes#130]
Bachigualato Federal International Airport 
(commonly known as Aeropuerto Internacional de Culiacán)
http://en.wikipedia.org/wiki/Bachigualato_Federal_International_Airport

The ASQ Award for "Best Airport with Fewer than 2 Million Passengers per Year" in Latin America-Caribbean region went to Culiacán International Airport in Mexico.
http://www.aci.aero/Airport-Service-Quality/ASQ-Awards/Current-Winners/Best-Regional-Airport/Latin-America--Caribbean

pics:
http://mexicoteve.com/timthumb.php?src=/web_imagenes/2013_38_1849445.jpg&h=277&w=655&zc=1
http://www.mazatlaninteractivo.com.mx/new/images/stories/memo/culiacan.jpg

**Comment by lynnandtonic** [comment]
Second photo CC: http://en.wikipedia.org/wiki/Bachigualato_Federal_International_Airport#/media/File:Culiacan_International_Airport_new_fa%C3%A7ade.jpg

by Lizreyesk
