### ISSUE TITLE
+- YYC

### ISSUE THREAD

**Issue by litratomoto** [lynnandtonic/airport-codes#134]
Calgary International Airport (YYC

**Comment by ncrohn** [comment]
http://en.wikipedia.org/wiki/Calgary_International_Airport

Photo: https://www.flickr.com/photos/jordoncooper/1446448/in/photolist-8pYL-8pYJ-8pYu-8fMkQw-8pZ7-8pYP-d8Nm5C-81kUHy-8fMaLm-6HZ7f5-8LgdJ4-75x447-7GxVM9-77Bi6S-8KoHNL-7u2sJK-qiRFo-749VvJ-6BTyrL-51kUrC-7XR9Dw-9qK8E4-KXQyL-8iu157-is2Lg-cwSDKm-7Btqgb-2tM4p9-bKuLBR-8i4L8Y-7AUKR2-7AUPdV-KXQnd-8XErqi-qiRNu-8g2qzd-9stWs4-6UQzeL-8Ph6ac-7H186o-7u2p2M-qiRDy-7SEzH5-8Qfwkm-85mk7U-7dbDfr-7k64ck-6GQH8d-7ooL1f-6VSKYb

**Comment by lynnandtonic** [comment]
https://twitter.com/brianleekim/status/582531239665528833

**Comment by lynnandtonic** [comment]
An explanation of the YC: https://twitter.com/biffmunky/status/583261490834108416

**Comment by ncrohn** [comment]
https://twitter.com/chikom/status/583664214872498176
