### ISSUE TITLE
Morocco Airports

### ISSUE THREAD

**Issue by ayoubgdah** [lynnandtonic/airport-codes#135]
- [ ] CMN: Mohammed V International Airport 
- [x] RAK: Marrakesh Menara Airport
- [ ] FEZ: Fes–Saïss Airport
- [ ] AGA: Agadir–Al Massira Airport
- [ ] RBA: Rabat–Salé Airport
- [ ] TNG: Tangier Ibn Battouta Airport

**Comment by lynnandtonic** [comment]
CMN: https://www.flickr.com/photos/dandiffendale/16157444733
RAK: https://www.flickr.com/photos/thomasleuthard/8446832731
FEZ: https://www.flickr.com/photos/furumaru/5791931376
AGA: https://www.flickr.com/photos/gaizko/3226643214
RBA: 
TNG: https://www.flickr.com/photos/calflier001/8699152339
