### ISSUE TITLE
+TPE

### ISSUE THREAD

**Issue by julia00** [lynnandtonic/airport-codes#136]

**Comment by lynnandtonic** [comment]
http://en.wikipedia.org/wiki/Taoyuan_International_Airport

A few photos I'm thinking:
https://www.flickr.com/photos/kentaroiemoto/4039667508
https://www.flickr.com/photos/bryansjs/15987865602
https://www.flickr.com/photos/azerila/2665022145
https://www.flickr.com/photos/tobysimkin/4749046347

**Comment by julia00** [comment]
Great!
