### ISSUE TITLE
+ HOG, PEE, POO

### ISSUE THREAD

**Issue by lynnandtonic** [lynnandtonic/airport-codes#142]
https://twitter.com/jarheadesign/status/578535233387114497

- [x] HOG
- [x] PEE
- [ ] POO

**Comment by lynnandtonic** [comment]
### HOG
http://en.wikipedia.org/wiki/Frank_Pa%C3%ADs_Airport
https://www.flickr.com/photos/cleverboy68/431711434

### PEE
http://en.wikipedia.org/wiki/Perm_International_Airport
https://www.flickr.com/photos/killerbass/466023004/in/photolist-9hAeV2-oES1PD-Hbupo-4yCdgJ

### POO
http://en.wikipedia.org/wiki/Po%C3%A7os_de_Caldas

**Comment by ncrohn** [comment]
Added HOG.

For Perm I found a better photo here: http://www.airlines-inform.com/upload/reviews_pictures/1200-upload-blog-433-rusline-embraer-120-47.jpg

Will need to request permission to use it.
