### ISSUE TITLE
NCL

### ISSUE THREAD

**Issue by mattbriggs87** [lynnandtonic/airport-codes#156]
![and_1507smaller](https://cloud.githubusercontent.com/assets/11557166/6733403/f585ffe0-ce49-11e4-96ad-d4e1bce97e45.jpg)
Newcastle International Airport
Newcastle, UK
Opened in 1935, Newcastle International Airport served 4.6 million passengers in 2014 making it one of the largest in the United Kingdom.

**Comment by lynnandtonic** [comment]
@mattbriggs87 Do you have a link to where you got that image from?

**Comment by mattbriggs87** [comment]
Hi Lynn. It's from the airport's own photo library. It's not online.

On 21 March 2015 at 02:23, Lynn Fisher <notifications@github.com> wrote:

> @mattbriggs87 <https://github.com/mattbriggs87> Do you have a link to
> where you got that image from?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lynnandtonic/airport-codes/issues/156#issuecomment-84220305>
> .
>



-- 
*Matt Briggs *MCIPR
*mobile:* 07540 574139
* email:* mattbriggs87@gmail.com
*web: *www.theonlinerule.com
*twitter:* @MattBriggsPR <http://twitter.com/MattBriggsPR>

**Comment by lynnandtonic** [comment]
@mattbriggs87 Oh! Awesome. Who would you like me to credit/link to for the photo? I could link to the airport's website or twitter as examples.

**Comment by mattbriggs87** [comment]
Hi Lynn. The website would be best - http://www.newcastleairport.com/

On 22 March 2015 at 14:38, Lynn Fisher <notifications@github.com> wrote:

> @mattbriggs87 <https://github.com/mattbriggs87> Oh! Awesome. Who would
> you like me to credit/link to for the photo? I could link to the airport's
> website or twitter as examples.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lynnandtonic/airport-codes/issues/156#issuecomment-84620759>
> .
>



-- 
*Matt Briggs *MCIPR
*mobile:* 07540 574139
* email:* mattbriggs87@gmail.com
*web: *www.theonlinerule.com
*twitter:* @MattBriggsPR <http://twitter.com/MattBriggsPR>

**Comment by lynnandtonic** [comment]
Thank you so much! I'll get this deployed soon. :)
