### ISSUE TITLE
Photo used in GIG is from SDU

### ISSUE THREAD

**Issue by racporto** [lynnandtonic/airport-codes#171]
The photograph used to illustrate GIG - Galeão International Airport of Rio de Janeiro, AKA Antonio Carlos Jobim Airport, is from SDU's departure lounge. SDU stands for Santos Dumont Airport, Rio de Janeiro's regional airport. As the GIG airport is undergoing massive renovation, in a complete mess, I couldn't find any good CC photo from Flickr, except this one, from the fountains beneath the escalators of terminal 1: https://www.flickr.com/photos/denysalmeida/3805424525

**Comment by lynnandtonic** [comment]
Thank you for the info! I corrected the photo and added SDU. :)

**Comment by racporto** [comment]
My pleasure, I assure you. It's such a cool page.

Congratulations, and thanks for the effort of putting it all together.

Cheers,
Ricardo Porto
diretor executivo | managing director
Calepino - ilimite-se!
http://www.calepino.com
http://www.webtexto.com.br
