### ISSUE TITLE
BGW

### ISSUE THREAD

**Issue by JeremiCz** [lynnandtonic/airport-codes#195]
It is the Baghdad International Airport. B and G are obvious, W is apparently random as more obvious combinations were taken by minor airports.

Originally the airport was called "Saddam Hussein International" and its code was "SDA", which both got changed after Hussein was deposed. Interestingly, you can still "fly" to SDA, as the code was reallocated to the long-distance bus station in Saarbrucken, where Lufthansa "flies" in with their coaches from FRA. Some reservation systems still tell you you fly to Saddam Hussein when you book the connection.

**Comment by lynnandtonic** [comment]
http://en.wikipedia.org/wiki/Baghdad_International_Airport

https://www.flickr.com/photos/toyohara/12320289523

**Comment by lynnandtonic** [comment]
Thank you, @JeremiCz!
