### ISSUE TITLE
+ KIX

### ISSUE THREAD

**Issue by lynnandtonic** [lynnandtonic/airport-codes#207]
https://twitter.com/ro_sutobi_fu/status/578875061890867200

**Comment by lynnandtonic** [comment]
http://en.wikipedia.org/wiki/Kansai_International_Airport

https://www.flickr.com/photos/andihalimphotography/8976391919
https://www.flickr.com/photos/fireballsg72/8089841339

**Comment by as2895** [comment]
{
"id": "kix",
"code": "kix",
"name": "Kansai International Airport",
"city": "Osaka",
"state": "",
"stateShort": "",
"country": "Japan",
"description": "Fully built on an artificial island, the airport serves the city of Osaka. The code comes from the region it sits at, *K*ansa*i*, with a letter *X* at the end. ",
"imageCredit": "",
"imageCreditLink": ""
}
