### ISSUE TITLE
VPS

### ISSUE THREAD

**Issue by FlyVPS** [lynnandtonic/airport-codes#215]
VPS is the three letter identifier for the Destin-Fort Walton Beach Airport and is derived from the town of Valparaiso which is adjacent to the airport.
![image](https://cloud.githubusercontent.com/assets/11577563/6760988/59f47f9c-cf1c-11e4-8c7d-27b323dd75c0.jpg)

**Comment by FlyVPS** [comment]
ValParaiSo also stands for Very Pretty Sand.

**Comment by lynnandtonic** [comment]
@FlyVPS Do you have a high-res photo you'd give us permission to use?

**Comment by FlyVPS** [comment]
Hi Lynn,

A few photos are attached and for your use. I look forward to seeing VPS up on your site.

![1vps 166](https://cloud.githubusercontent.com/assets/11577563/6902124/6ae60b5a-d6d7-11e4-89e2-c209d7a5cbd3.jpg)
![vps 015](https://cloud.githubusercontent.com/assets/11577563/6902130/7b193baa-d6d7-11e4-8c93-d7f7971e766c.jpg)
![vps 183](https://cloud.githubusercontent.com/assets/11577563/6902133/82bd4b9e-d6d7-11e4-89aa-74f31ec67d08.jpg)
![vps 114](https://cloud.githubusercontent.com/assets/11577563/6902137/8b796600-d6d7-11e4-9e9c-78a9ff19c7c0.jpg)

See you around Chandler!

Have a great day.

Mike

**Comment by lynnandtonic** [comment]
Thank you, @FlyVPS! We'll push it live to the site soon.

**Comment by FlyVPS** [comment]
Awesome. Thanks.

Michael J. Stenson
Deputy Director
Okaloosa County Airports

On Apr 2, 2015, at 10:29 AM, Lynn Fisher <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you, @FlyVPS<https://github.com/FlyVPS>! We'll push it live to the site soon.
