### ISSUE TITLE
+ MVD is the airport in Montevideo, Uruguay

### ISSUE THREAD

**Issue by iign** [lynnandtonic/airport-codes#227]
Carrasco International Airport (actual name is "General Cesáreo L. Berisso International Airport", but is widely known for the former, even on Wikipedia)
http://en.wikipedia.org/wiki/Carrasco_International_Airport

Photograph https://www.flickr.com/photos/arlekom/4731871696

**Comment by lynnandtonic** [comment]
:+1:
