### ISSUE TITLE
+ AEP

### ISSUE THREAD

**Issue by lynnandtonic** [lynnandtonic/airport-codes#235]
https://twitter.com/renzo_adriano/status/579449752766558208

**Comment by lynnandtonic** [comment]
https://twitter.com/tuliopb/status/581173601229008896

**Comment by cristianxb1983** [comment]
{
    "id": "aep",
    "code": "aep",
    "name": "Aeroparque Jorge Newbery",
    "city": "Ciudad Autonoma de Buenos Aires",
    "state": "",
    "stateShort": "",
    "country": "Argentina",
    "description": "The Aeroparque Jorge Newbery serves as the main airport for the city of Buenos Aires. serving both domestic and regional markets. Its airport code comes from its name  AEroParque",
  
}

**Comment by lynnandtonic** [comment]
https://twitter.com/sol_mafu/status/582525254020538369

**Comment by lynnandtonic** [comment]
Thank you, @cristianxb1983!
