### ISSUE TITLE
+SUN

### ISSUE THREAD

**Issue by skellywright** [lynnandtonic/airport-codes#249]
IATA code SUN
Friedman Memorial Airport
Hailey (also known for Sun Valley)
Idaho 
ID
USA

Image link: http://bit.ly/1BHk7SN
Photo by DieselDemon
https://www.flickr.com/photos/28096801@N05/

**Comment by patilchetan** [comment]
Added: https://github.com/lynnandtonic/airport-codes/pull/262

**Comment by patilchetan** [comment]
Added: https://github.com/lynnandtonic/airport-codes/pull/265
