### ISSUE TITLE
+SJJ

### ISSUE THREAD

**Issue by skellywright** [lynnandtonic/airport-codes#251]
IATA code SJJ
Sarajevo International Airport
(also known as Butmir airport)
Sarajevo
Bosnia And Herzegovina

image link: http://bitly.com/1IhcRCN
Photo by elrina753
https://www.flickr.com/photos/elrina753/

**Comment by lynnandtonic** [comment]
Thank you, @skellywright! The photo you linked to is a copyrighted image, so we couldn't use it. I found another one that looks pretty good. Thanks again!
