### ISSUE TITLE
Please optimize images?

### ISSUE THREAD

**Issue by vjo** [lynnandtonic/airport-codes#261]
What do you mean by "Please optimize images"?
Is it acceptable for you to reduce the quality of an image?

I have made some test for a given image, using imagemagick [0] and these commands:
```
convert -interlace Plane -quality 85% -strip original.jpg -resize x250 card/lcy-quality-85.jpg
```
```
convert -interlace Plane -strip original.jpg -resize x250 card/lcy-quality-100.jpg
```
For a `card` image in this case, the size drop is significant:
63K lcy-quality-100.jpg
23K lcy-quality-85.jpg

The differences between both images without zooming is hardly noticeable.

Would be great if we can all share the same methods for optimizing images.

Thanks,
Victor

[0] http://www.imagemagick.org/

**Comment by ncrohn** [comment]
Hey Victor,

We weren't super clear on that, as we were mostly trying to limit barrier to entry to contribute. The main goal was to just have the images optimized as best as the contributor could do. We double check them before we deploy, so if they can be compressed more we'll do that.

That being said we'll look into adding image optimization into the build process to simplify and streamline the whole step.

For now I'd say keep doing what you're doing. We've been using [ImageOptim](https://imageoptim.com/) to optimize currently.

**Comment by matiassingers** [comment]
@ncrohn did you guys look into just having 1 large format image in the repo, and then generate the smaller sizes on deploy?

Would help with the pretty crazy repo size right now.

**Comment by ncrohn** [comment]
I had thought about doing that, but didn't want to force the requirement of having an external dependency on something like ImageMagick. That being said the repo is starting to get quite large, over 500mb right now.

I'm going to start digging into this and see what we can do about the repo size while also maintaining ease of use for contributors.

**Comment by lynnandtonic** [comment]
We've decided to leave image optimization as is for now.

Thank you for your thoughts and input!
