### ISSUE TITLE
+TPA - Tampa International Airport

### ISSUE THREAD

**Issue by dwhitejr** [lynnandtonic/airport-codes#275]
id = TPA
    code = TPA
    name = *T*am*p**a* International Airport
    city = Tampa
    state = Florida
    stateShort = FL
    country = USA
    description = Formerly known as *D*rew *F*ield, and birthplace of the commercial airline service.  One of the world's most loved airports, TPA services the greater St. Petersburg-Tampa (Tampa Bay) area.
    imageCredit = Artie White
    imageCreditLink = https://www.flickr.com/photos/42105353@N02/8077728605

**Comment by patilchetan** [comment]
@lynnandtonic:

Added: https://github.com/lynnandtonic/airport-codes/pull/322
