### ISSUE TITLE
PNQ could use a better photo

### ISSUE THREAD

**Issue by lynnandtonic** [lynnandtonic/airport-codes#288]
Let's maybe reach out to the airport for a better high-res photo.

**Comment by patilchetan** [comment]
Official Airport Authority of India's (AAI) Pune airport [page](http://www.aai.aero/allAirports/pune_generalinfo.jsp). Good images are there, but no clarity on whether under CC or not.

Direct [link](http://www.aai.aero/images/pune_airpoet_big.swf) to slideshow.

**Comment by lynnandtonic** [comment]
Going to leave for now.
