### ISSUE TITLE
Piedmont Triad International 

### ISSUE THREAD

**Issue by hefnertw** [lynnandtonic/airport-codes#289]
PTI serves the Piedmont Triad area of North Carolina.  This includes the area of Greensboro, High Point and Winston-Salem. The initials come from the first letter in each word.

We are in the middle of the Piedmont and the three cities above are the big cities in the Triad region.  (The Triangle area served by RDU airport is a bit to the east and includes Raleigh, Durham, and Chapel Hill.)

**Comment by lynnandtonic** [comment]
Thank you, @hefnertw!

**Comment by hefnertw** [comment]
Excellent.  I told the story of the name and forgot to mention the code GSO.  But you figured it out.  Sorry for making you do the extra work.

**Comment by lynnandtonic** [comment]
@hefnertw no problem at all! :)
