### ISSUE TITLE
SLC

### ISSUE THREAD

**Issue by metasean** [lynnandtonic/airport-codes#32]
Info:
 - Salt Lake City International Airport 
 - https://en.wikipedia.org/wiki/Salt_Lake_City_International_Airport

Images:
 - http://www.slcairport.com/image-library.asp
 - https://commons.wikimedia.org/wiki/Category:Salt_Lake_City_International_Airport

**Comment by lynnandtonic** [comment]
Thank you @metasean! SLC has been added and will be deployed to production soon. :)

**Comment by metasean** [comment]
@lynnandtonic - Thank you for such a cool way to explore airport codes!
