### ISSUE TITLE
LIH

### ISSUE THREAD

**Issue by qEgkoot** [lynnandtonic/airport-codes#320]
{
	"id": "lih",
	"code": "lih",
	"name": "Lihue Airport",
	"city": "Lihue",
	"city2": "Kauai",
	"state": "Hawaii",
	"stateShort": "HI",
	"country": "USA",
	"description": "Opened in 1949, this is the primary airport on the Island of Kauai. It gets its name and airport code from its home in *L**i**h*ue.",
	"imageCredit": " Wally Gobetz",
	"imageCreditLink": "https://www.flickr.com/photos/wallyg/4698109914/"
}

![lih-wally-gobetz_large](https://cloud.githubusercontent.com/assets/11651428/6830663/90eff5ca-d2d8-11e4-92db-e31567565449.jpg)
![lih-wally-gobetz_med](https://cloud.githubusercontent.com/assets/11651428/6830666/96c37c74-d2d8-11e4-9ca9-38bd94bbbbe9.jpg)
![lih-wally-gobetz_small](https://cloud.githubusercontent.com/assets/11651428/6830669/991ac7a2-d2d8-11e4-9855-b2bf3e467cec.jpg)
![lih-wally-gobetz_card](https://cloud.githubusercontent.com/assets/11651428/6830671/9bacd118-d2d8-11e4-8ccf-79905cda046c.jpg)

**Comment by patilchetan** [comment]
@lynnandtonic:

Added: https://github.com/lynnandtonic/airport-codes/pull/322
