### ISSUE TITLE
LIN

### ISSUE THREAD

**Issue by qEgkoot** [lynnandtonic/airport-codes#321]
{
	"id": "lin",
	"code": "lin",
	"name": "Aeroporto di Milano-Linate",
	"nameEnglish": "Milan Linate Airport",
	"city": "Milan",
	"city2": "Linate",
	"state": "",
	"stateShort": "",
	"country": "Italy",
	"description": "Opened in 1960, this is Milan's city airport, located 20 miles closer to the center than Malpensa. Officially named Airport Enrico Forlanini, it gets its name and airport code from the village where its located, *L**i**n*ate.",
	"imageCredit": "Stefano F",
	"imageCreditLink": "https://www.flickr.com/photos/stefof/6797872866/"
}
![lin-stefano-f_large](https://cloud.githubusercontent.com/assets/11651428/6831870/4c96c37e-d2e0-11e4-9329-c774dce0b7ff.jpg)
![lin-stefano-f_medium](https://cloud.githubusercontent.com/assets/11651428/6831873/4eee1b18-d2e0-11e4-94ae-adefce3f8eeb.jpg)
![lin-stefano-f_small](https://cloud.githubusercontent.com/assets/11651428/6831874/50d61822-d2e0-11e4-9d25-505b8255643c.jpg)
![lin-stefano-f_card](https://cloud.githubusercontent.com/assets/11651428/6831878/53262522-d2e0-11e4-9547-0b5ad48208a6.jpg)

**Comment by lynnandtonic** [comment]
Thank you! :)
