### ISSUE TITLE
ANU

### ISSUE THREAD

**Issue by qEgkoot** [lynnandtonic/airport-codes#332]
{
	"id": "anu",
	"code": "anu",
	"name": "V. C. Bird International Airport",
	"city": "Saint John's",
	"state": "",
	"stateShort": "",
	"country": "Antigua and Barbuda",
	"description": "Originally built in 1942 by the United States for military use. The base was turned over to the government of Antigua and Barbuda in 1949 and became Coolidge Airport. It was renamed in 1985 in honor of the country's first Premiere Vere Cornwall Bird Sr. The code comes from the island's name *A**N*tig*U*a.",
	"imageCredit": "Lee Bryant",
	"imageCreditLink": "https://www.flickr.com/photos/alihodza/334448631/"
}
![anu-lee-bryant_large](https://cloud.githubusercontent.com/assets/11651428/6836778/c955b51a-d302-11e4-81e4-ed15e82f05d2.jpg)
![anu-lee-bryant_medium](https://cloud.githubusercontent.com/assets/11651428/6836781/cb63e714-d302-11e4-9486-454d9de1a5e0.jpg)
![anu-lee-bryant_small](https://cloud.githubusercontent.com/assets/11651428/6836782/cdb762fc-d302-11e4-96bf-2da8d994b558.jpg)
![anu-lee-bryant_card](https://cloud.githubusercontent.com/assets/11651428/6836785/cf9b0ed4-d302-11e4-98a8-308f8ba24700.jpg)

Alternate Image
{
	"imageCredit": "Stefan Krasowski",
	"imageCreditLink": "https://www.flickr.com/photos/rapidtravelchai/15476450550/"
}
![anu-stefan-krasowski_large](https://cloud.githubusercontent.com/assets/11651428/6903750/60ab8b20-d6d1-11e4-9183-48c5390ae8c8.jpg)
![anu-stefan-krasowski_medium](https://cloud.githubusercontent.com/assets/11651428/6903753/63315ca8-d6d1-11e4-9c0e-77ad6fd6260c.jpg)
![anu-stefan-krasowski_small](https://cloud.githubusercontent.com/assets/11651428/6903757/650ed0a0-d6d1-11e4-97a5-8e6cce9dc6c6.jpg)
![anu-stefan-krasowski_card](https://cloud.githubusercontent.com/assets/11651428/6903763/68bae392-d6d1-11e4-9ca5-20270e712771.jpg)

**Comment by lynnandtonic** [comment]
Thank you, @qEgkoot!
