### ISSUE TITLE
TGU

### ISSUE THREAD

**Issue by qEgkoot** [lynnandtonic/airport-codes#336]
{
	"id": "tgu",
	"code": "tgu",
	"name": "Aeropuerto Internacional Toncontín",
	"nameEnglish": "Toncontín International Airport",
	"city": "Tegucigalpa",
	"state": "",
	"stateShort": "",
	"country": "Honduras",
	"description": "A notoriously difficult airport for landing, Toncontín opened in 1933, and gets its code from the city in which it is located *T*e*G**U*cigalpa, the capital of Honduras",
	"imageCredit": "enrique",
	"imageCreditLink": "https://www.flickr.com/photos/egm757lover/2120465227/"
}
![tgu-enrique_large](https://cloud.githubusercontent.com/assets/11651428/6837876/29a2f836-d30f-11e4-8546-5a0200129ea1.jpg)
![tgu-enrique_medium](https://cloud.githubusercontent.com/assets/11651428/6837879/2bf4092c-d30f-11e4-8e6a-dc3cbf71c5f2.jpg)
![tgu-enrique_small](https://cloud.githubusercontent.com/assets/11651428/6837881/2dda3cf2-d30f-11e4-89cd-3df500463c97.jpg)
![tgu-enrique_card](https://cloud.githubusercontent.com/assets/11651428/6837884/3061a384-d30f-11e4-9be9-6b32284e8995.jpg)

**Comment by lynnandtonic** [comment]
Thank you, @qEgkoot!
