### ISSUE TITLE
GUA

### ISSUE THREAD

**Issue by qEgkoot** [lynnandtonic/airport-codes#337]
{
	"id": "gua",
	"code": "gua",
	"name": "Aeropuerto Internacional La Aurora",
	"nameEnglish": "La Aurora International Airport",
	"city": "Guatemala City",
	"state": "",
	"stateShort": "",
	"country": "Guatemala",
	"description": "The airport was developed as *G**U**A*temala City Air Base by the United States Army Air Forces during World War II. In 1949, the base was closed and handed over to Guatemala. Today it is the primary airport in Guatemala and one of the busiest in Central America.",
	"imageCredit": "xiroro",
	"imageCreditLink": "https://www.flickr.com/photos/xiroro/15485743564/"
}
![gua-xiroro_large](https://cloud.githubusercontent.com/assets/11651428/6837891/487a1d66-d30f-11e4-8acb-5442c2307062.jpg)
![gua-xiroro_medium](https://cloud.githubusercontent.com/assets/11651428/6837892/4a79c878-d30f-11e4-82a3-a1dcb44de76f.jpg)
![gua-xiroro_small](https://cloud.githubusercontent.com/assets/11651428/6837893/4cb46a30-d30f-11e4-8a0c-0e050b646182.jpg)
![gua-xiroro_card](https://cloud.githubusercontent.com/assets/11651428/6837894/4eea954a-d30f-11e4-9e8a-474bd7438547.jpg)

**Comment by lynnandtonic** [comment]
Thank you @qEgkoot!
