### ISSUE TITLE
AVP

### ISSUE THREAD

**Issue by rabbitupnorth** [lynnandtonic/airport-codes#338]
Scranton-Wilkes Barre, Pennsylvania (PA, USA) airport is located in AVoca Pennsylvania, thus the AVP code. Part of the runway runs into Moosic PA.
Image is from wikipedia article, licensed under the Creative Commons Attribution-Share Alike 3.0 Unported license.
![avp-kavp_pano](https://cloud.githubusercontent.com/assets/11657710/6839515/e9798348-d33f-11e4-8435-9296eb0af4e3.jpg)
- Rabbitupnorth, Hamilton, ON, Canada

**Comment by lynnandtonic** [comment]
https://twitter.com/dsalko/status/583313921324498944

**Comment by lynnandtonic** [comment]
Thank you, @rabbitupnorth! Good stuff. :)
