### ISSUE TITLE
HAM

### ISSUE THREAD

**Issue by davidgorges** [lynnandtonic/airport-codes#343]
{
"id": "ham",
"code": "ham",
"name": "Hamburg Airport"
"nameEnglish": "Hamburg Airport"",
"city": "Hamburg",
"state": "",
"stateShort": "",
"country": "Germany",
"description": "Hamburg Airport is located about 5 miles outside Hamburg, Germany's second largest city.",
"imageCredit": "Joerg Moellenkamp",
"imageCreditLink": "https://www.flickr.com/people/54617889@N00/"
}

https://flic.kr/p/6j9yC
![Terminal 1](https://farm1.staticflickr.com/30/60123300_407056c372.jpg)

**Comment by lynnandtonic** [comment]
Thank you!
