### ISSUE TITLE
+ Vietnam airports

### ISSUE THREAD

**Issue by lynnandtonic** [lynnandtonic/airport-codes#350]
https://twitter.com/huuluannhan/status/580985136067416064

He would like to be notified once they are added.

I'll make a checklist here in a bit.

**Comment by patilchetan** [comment]
## Added

DAD: https://github.com/lynnandtonic/airport-codes/pull/364

## Left
- [ ] HAN
- [ ] SGN
- [ ] CXR
- [ ] PQC
- [ ] HPH
- [ ] VCL
- [ ] VII 
- [ ] BMV
- [ ] VCS
- [ ] VCA
- [ ] UIH
- [ ] CAH
- [ ] DIN
- [ ] PXU
- [ ] VKG
- [ ] TBB
- [ ] VHD

**Comment by lynnandtonic** [comment]
HAN: https://twitter.com/smith_pk/status/598811638230347776
