### ISSUE TITLE
Want to contribute SAT and SSF to your site

### ISSUE THREAD

**Issue by CatalinaVelez** [lynnandtonic/airport-codes#353]
Hello, first off thank you for doing such a cool site. Second, i would like to contribute 2 airports to the site. I currently work for the marketing department at San Antonio International Airport and would like to add SAT and SSF to your site. I have the content and images that I can provide to you as well.

Catalina Velez-Watson.

**Comment by patilchetan** [comment]
@lynnandtonic:

Added: https://github.com/lynnandtonic/airport-codes/pull/357

**Comment by CatalinaVelez** [comment]
Lynn, does this mean it's done? Sorry I'm just not understanding why the emails. Lol.

Catalina "Cat" Velez-Watson

Sent from iPhone.

On Mar 26, 2015, at 9:05 PM, Lynn Fisher <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #353<https://github.com/lynnandtonic/airport-codes/issues/353>.

**Comment by lynnandtonic** [comment]
Hi Catalina,

Yes. The work has been done. I will be pushing the update to the live site later tonight. Thanks!

**Comment by CatalinaVelez** [comment]
Wow. Amazing. I'm not going to get tired of saying you guys are great. ;) good night.

Catalina "Cat" Velez-Watson

Sent from iPhone.

On Mar 26, 2015, at 9:30 PM, Lynn Fisher <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Catalina,

Yes. The work has been done. I will be pushing the update to the live site later tonight. Thanks!
