### ISSUE TITLE
+YHZ - Halifax Stanfield International Airport

### ISSUE THREAD

**Issue by MikeSQ** [lynnandtonic/airport-codes#39]
[Relevant Wikipedia article](http://en.wikipedia.org/wiki/Halifax_Stanfield_International_Airport)

Looking at the wiki and at the [official site](http://hiaa.ca/), I still don't know why it is YHZ

**Comment by lynnandtonic** [comment]
https://www.flickr.com/photos/cgc/501504534

**Comment by mseymour** [comment]
Can't find anything either. "H" probably stands for "Halifax".

**Comment by patilchetan** [comment]
@MikeSQ @lynnandtonic @mseymour:

Many airport codes are as per code series started by IATA after it ran out of naming airports based on city or airport name. So, if you check [this wiki page](http://en.wikipedia.org/wiki/List_of_airports_by_IATA_code:_Y#YH), then, **YH** is the code series, and then **Z** is the letter allocated as per the sequence.
