### ISSUE TITLE
+ CBR

### ISSUE THREAD

**Issue by craigie82** [lynnandtonic/airport-codes#412]
Canberra International Airport, is the airport serving Australia's capital city, Canberra, the nearby city of Queanbeyan, NSW and the surrounding regional area of South-Eastern New South Wales.
![92541983](https://cloud.githubusercontent.com/assets/11711360/6888545/49be0a22-d6cd-11e4-8d79-9753929863db.jpg)

**Comment by craigie82** [comment]
It has content and a picture!

**Comment by lynnandtonic** [comment]
@craigie82 Yes, thanks for your contribution! Do you have a link to where that photo came from? Or is it an original by you?

**Comment by craigie82** [comment]
Picture link: http://static.panoramio.com/photos/large/92541983.jpg

**Comment by lynnandtonic** [comment]
@craigie82 Sorry, I should have been more specific. Is this a photo by you or do you know who the photographer is?
