### ISSUE TITLE
+ CMB

### ISSUE THREAD

**Issue by lynnandtonic** [lynnandtonic/airport-codes#420]
https://twitter.com/pradeeban/status/582341909395480577

**Comment by patilchetan** [comment]
@lynnandtonic:

Added: https://github.com/lynnandtonic/airport-codes/pull/424

**Comment by lynnandtonic** [comment]
https://twitter.com/mulaafer/status/582537000865153025

**Comment by lynnandtonic** [comment]
https://twitter.com/sasithemedico/status/582606495281348608
