### ISSUE TITLE
+ CTG

### ISSUE THREAD

**Issue by ncrohn** [lynnandtonic/airport-codes#471]
https://twitter.com/carlitos_hdz/status/582540405343969280

http://en.wikipedia.org/wiki/Rafael_N%C3%BA%C3%B1ez_International_Airport

**Comment by patilchetan** [comment]
@ncrohn @lynnandtonic:

Added: https://github.com/lynnandtonic/airport-codes/pull/477

**Comment by lynnandtonic** [comment]
https://twitter.com/avillavec/status/583453034233069568
