### ISSUE TITLE
+ OTP

### ISSUE THREAD

**Issue by JustDoIt17** [lynnandtonic/airport-codes#48]
Henri Coandă International Airport

http://en.wikipedia.org/wiki/Henri_Coand%C4%83_International_Airport

**Comment by campuscodi** [comment]
Bucharest's Henri Coandă International Airport honors Henri Coandă, inventor of the first jet engine and discoverer of the Coandă effect in fluid dynamics, but takes its airport code from the city of OToPeni, a small city near Romania's capital.

Some sample images, but there are loads more on Flickr:
https://www.flickr.com/photos/bortescristian/8578844466/in/photostream/
https://www.flickr.com/photos/bortescristian/8577737815

**Comment by lynnandtonic** [comment]
Thank you, @JustDoIt17 and @campuscodi! :)

**Comment by campuscodi** [comment]
There's a mistake on the site. It's not Budapest's airport. It's Bucharest's airport..... since we're talking about Eastern Europe... congratulations! You've just started another war! :))))

**Comment by lynnandtonic** [comment]
Whoops! Thanks for catching that. All fixed. :)
