### ISSUE TITLE
ZIH

### ISSUE THREAD

**Issue by nm1000** [lynnandtonic/airport-codes#487]
Ixtapa Zihuatanejo International Airport (ZIH) - I used to be in the airline business many years ago and we used to refer to this code "as the last city in the OAG". OAG was the Official Airline Guide publication that airline personnel referred to for flight times and codes.  (Of course it appears that the airline code would no longer have this distinction.)

Sorry, but don't have much background on the name but the airport code was specifically for Zihuatanejo before they added the city of of Ixtapa.  (I used to fly there in the early 70's.)  

Hope this helps.  

Nancy M.

**Comment by lynnandtonic** [comment]
Thank you, @nm1000!
