### ISSUE TITLE
+ FLR

### ISSUE THREAD

**Issue by JustDoIt17** [lynnandtonic/airport-codes#50]
Florence Airport, Peretola

http://en.wikipedia.org/wiki/Florence_Airport,_Peretola

**Comment by lynnandtonic** [comment]
{
    "id": "flr",
    "code": "flr",
    "name": "Aeroporto di Firenze-Peretola",
    "nameEnglish": "Florence Airport, Peretola",
    "city": "Florence",
    "city2": "Peretola",
    "state": "Tuscany",
    "stateShort": "",
    "country": "Italy",
    "description": "Formally known as Amerigo Vespucci airport after the Italian cartographer, *Fl*o*r*ence Airport is located in the suburb of Peretola.",
    "imageCredit": "",
    "imageCreditLink": ""
}

**Comment by lynnandtonic** [comment]
https://www.flickr.com/photos/travelinglibrarian/10512285636/in/photolist-c9pf6W-6HpnVm-eoYTU8-jjJipX-jjGziB-jjLQz1-jjJnJE-jjJghG-n8ptRk-2Czf92-6zkK5v-6zG6Hm-33FerE-2CzeLx-4Yre1h-d3Vcpj-4QBBj8-h1Wdh5-h1Ws9J-d1YVoN
