### ISSUE TITLE
DKR (Dakar, Senegal)

### ISSUE THREAD

**Issue by elanfleisher** [lynnandtonic/airport-codes#522]
![elanfleisher_dkr_2235](https://cloud.githubusercontent.com/assets/11758906/6948171/3f15dd1c-d8ac-11e4-9a75-55d35cde82c2.jpg)

**Comment by elanfleisher** [comment]
Léopold Sédar Senghor International Airport, Dakar, Senegal (DKR)

**Comment by lynnandtonic** [comment]
Thank you, @elanfleisher!
