### ISSUE TITLE
BKO (Bamako, Mali)

### ISSUE THREAD

**Issue by elanfleisher** [lynnandtonic/airport-codes#523]
Bamako–Sénou International Airport, Bamako, Mali (BKO)
![elanfleisher_bko_4179](https://cloud.githubusercontent.com/assets/11758906/6948266/ee0e4de0-d8ac-11e4-9a5d-979d5e8b7210.jpg)

**Comment by lynnandtonic** [comment]
Thank you, @elanfleisher!
