### ISSUE TITLE
FSP (St. Pierre and Miquelon) St. Pierre's Pointe Blanche airport

### ISSUE THREAD

**Issue by peggykb9** [lynnandtonic/airport-codes#530]
FSP (St. Pierre and Miquelon) St.Pierre airport

**Comment by peggykb9** [comment]
![st pierre airport](https://cloud.githubusercontent.com/assets/11760529/6951348/3e833718-d880-11e4-81f1-0566a74a968d.jpg)

**Comment by lynnandtonic** [comment]
@peggykb9 Where did that photo come from? Do you have an original link for it? I need to see what license it has. Thanks!

**Comment by peggykb9** [comment]
Lynn, I don't know what license an original amateur photo would have.


We have the originals of the photos I submitted for Sydney NS (not Sydney NSW LOL), St. Pierre, and Miquelon. You can see me in the FSP shot walking into the terminal with the red roller bag. Paul DeWitte shot the photos using my camera. 


We have been to St. Pierre and Miquelon eight times so far. We did a PowerPoint on our vacation for some local ham radio groups and the airport photos were part of that program.

Our website is hamradio.pnpfarms.com if that helps. It does need a little updating to make it mobile-friendly.


Peg Haese and Paul DeWitte

________________________________

**Comment by lynnandtonic** [comment]
@peggykb9 Oh! I didn't realize these were your. So awesome! So we have your permission to use them then?

Would you mind emailing me the original files to lynn@lynnandtonic.com? (I need them to be at least 1500px wide)

Thank you!
