### ISSUE TITLE
MQC (St. Pierre and Miquelon) Miquelon airport

### ISSUE THREAD

**Issue by peggykb9** [lynnandtonic/airport-codes#531]
MQC (St. Pierre and Miquelon) Miquelon airport

**Comment by peggykb9** [comment]
![miquelon airport](https://cloud.githubusercontent.com/assets/11760529/6950329/c4efdbb8-d87f-11e4-8d40-a88937f43aac.jpg)

**Comment by lynnandtonic** [comment]
@peggykb9 Also this photo, do you know where you got it? I need to check the license. Thanks!

**Comment by peggykb9** [comment]
(repeat of answer to FSP St. Pierre Point Blanche airport except I'm not in this one)

Lynn, I don't know what license an original amateur photo would have.

We have the originals of the photos I submitted for Sydney NS (not Sydney NSW LOL and they do get confused), St. Pierre, and Miquelon. 


We have been to St. Pierre and Miquelon eight times so far. Really interesting place! Off the south coast of Newfoundland which you can see when it's clear, but they're French territory, on the euro, and use European power plugs. We drive 2000 miles to Sydney and take the eight-seater plane to St. Pierre. Our luggage never gets lost.


We did a PowerPoint on our vacation for some local ham radio groups and the airport photos were part of that program. Paul shot the photos using my point-and-shoot camera.

Our website is hamradio.pnpfarms.com if that helps. It does need a little updating to make it mobile-friendly.

Peg Haese and Paul DeWitte

________________________________

**Comment by lynnandtonic** [comment]
Thank you, @peggykb9! That photo wasn't quite large enough to use, so I found another one for now. Please feel free to email me a higher resolution one and I can swap them. :)
