### ISSUE TITLE
Feature request: airport coordinates and/or street address

### ISSUE THREAD

**Issue by barthermans** [lynnandtonic/airport-codes#534]
I would love to see a feature to add airport coordinates and/or street address.
One of the advantages would be to have the possibility to show the airports on a map.

https://twitter.com/bhermans/status/580480968705867776

**Comment by lynnandtonic** [comment]
@barthermans Thank you so much for your suggestion! We've been noodling on it for a while now and it could be an awesome feature. Right now, though, I don't think we're going to implement it. We might add it in the future, but for now we're going to keep things pretty focused and simple. Thanks again, we really appreciate it!
