### ISSUE TITLE
The city of Malmoe (Local: Malmö), Sweden, have gone from three to one abreviation

### ISSUE THREAD

**Issue by 630328** [lynnandtonic/airport-codes#535]
The smal city of Malmoe (with Swedish letters: Malmö; the last letter an "o" with two dots on top) have lately had three abreviations that still causes some confusion. Some 30 years back the city center airport Bulltofta was scrapped and the runway beton was used to make a highway (E6 south of Malmoe). In Bulltofta's place the airport of Malmoe/Sturup was built, 20 minutes drive outside the 250 000 people-city. The new Malmoe/Sturup airport has always been called MMX. But, since little Malmoe needed good connections with the big, Danish Copenhagen Airport CPH, a stone threw away from Malmoe two solutions was in use during the 80s and 90s. Scandinavian Airlines, SAS, call sign SK, established a hydrofoil link between Malmoe harbor MMA and Copenhagen. Parallel to that a private Company called Helikopterservice AB (situated in the town of Helsingborg (opposite the narrow sound with Danish Helsingoer (in Danish Helsingør, the so called Hamlet Castle)), established a helicopter link from a separate Malmoe helipad HMA to Copenhagen. All that is now history since a bridge+tunnel has been built across the water stretch Oeresund betwen Malmoe and Copenhagen and it only take less than ten minutes to drive or even shorter time to go by train betwen the small Swedish town of Malmoe and the million plus Danish capital Copenhagen.
dahl.sverker@gmail.com

**Comment by lynnandtonic** [comment]
https://twitter.com/dfritzon/status/583329231226175488

**Comment by lynnandtonic** [comment]
Thank you, @630328! :+1:
