### ISSUE TITLE
+YMX

### ISSUE THREAD

**Issue by fcolpron** [lynnandtonic/airport-codes#536]
Content of ymx.json

{
	"id": "ymx",
	"code": "hyd",
	"name":	"ymx",
	"city":	"Mirabel",
	"city2": "Montreal",
	"state": "Quebec",
	"stateShort": "QC",
	"country": "Canada",
	"description": "With a few exceptions, airport codes starting with ‘*Y*’ designate Canadian airports. Mirabel Airport is mainly a cargo airport close to Montreal.",
	"imageCredit": "Yvan Leduc",
	"imageCreditLink": "http://upload.wikimedia.org/wikipedia/commons/5/59/NKN-2007-08-05_144714_MIRABEL_AIRPORT_control_tower_%28Yvan_Leduc_author_for_Wikipedia%29.Jpg"
}

**Comment by lynnandtonic** [comment]
Thank you, @fcolpron! :+1:
