### ISSUE TITLE
+ BFI

### ISSUE THREAD

**Issue by alexczaj** [lynnandtonic/airport-codes#567]
boeing Field International, aka King County International Airport is one of the busiest primary non-hub airports in the nation. Just four miles south of downtown Seattle, it averages around 200,000 operations (takeoffs and landings) each year. In 2001, it was named by the National Air Transportation Association as one of the “100 Most Needed Airports” in the United States. It is financed by airport tenants’ and customers’ fees, and receives no general tax revenues.

Boeing Field ranks among the most successful public investments in state history. The airport’s economic impact is $3.5 billion in terms of local business sales that support 16,336 jobs and create $1.8 billion in labor income in the county. The airport’s 150 tenant businesses also directly support 5,209 jobs in the local economy. (For details, see our 2013 economic impact study.)

The airport serves small commercial passenger airlines, cargo carriers, private aircraft owners, helicopters, corporate jets, and military and other aircraft. It is also home to the Boeing Company’s 737 aircraft flight-test program, along with other Boeing operations. The Museum of Flight is located there, with its wide variety of aircraft and exhibits showcasing aviation history. It is frequently host to celebrities and dignitaries, including the President of the United States, who prefer Boeing Field because of its proximity to downtown Seattle and other commercial areas.

**Comment by lynnandtonic** [comment]
Thank you, @alexczaj! :)

**Comment by alexczaj** [comment]
happy and proud to have contirbuted to this great fun project!
