### ISSUE TITLE
+DAL

### ISSUE THREAD

**Issue by neff** [lynnandtonic/airport-codes#57]
"id": "dal",
    "code": "dal",
    "name": "Dallas Love Field",
    "city": "Dallas",
    "state": "Texas",
    "stateShort": "TX",
    "country": "USA",
    "description": "Dallas Love Field is a city-owned public airport in Dallas Texas. It is named after Moss L. Love by the US Army in 1917. "

**Comment by lynnandtonic** [comment]
Thank you, @neff!
