### ISSUE TITLE
+ FNC

### ISSUE THREAD

**Issue by JPFJ** [lynnandtonic/airport-codes#578]
Madeira Airport (IATA: FNC, ICAO: LPMA), is the international airport of Madeira island in the Portuguese archipelago of Madeira.
The airport is famous for its runway which, surrounded by high mountains and the ocean, made it a tricky landing for even the most experienced of pilots. Nevertheless it is still considered one of the most dangerous airports in the world.

Image:
http://interestingengineering.com/wp-content/uploads/2014/02/Madeira-Airport-62.jpg

**Comment by lynnandtonic** [comment]
https://twitter.com/depandelaere/status/583927501958832128
