### ISSUE TITLE
AJL - Lengpui Airport

### ISSUE THREAD

**Issue by redbullpeter** [lynnandtonic/airport-codes#601]
AJL is the code for Lengpui Aiport which is the main airport for Aizawl the capital city of the state of Mizoram in India. The AJL code is derived from the alternative spelling of Aijawl which is the English transliteration of आइजोल which itself is a corrupted Hindi transliteration of the actual name.The code AZL was already taken by Fazenda Tucunaré an airport in Brazil.

**Comment by patilchetan** [comment]
@redbullpeter, @lynnandtonic:

Added: https://github.com/lynnandtonic/airport-codes/pull/669
