### ISSUE TITLE
+ Brazil airports

### ISSUE THREAD

**Issue by lynnandtonic** [lynnandtonic/airport-codes#609]
- [x] FOR
- [x] NAT
- [x] MAO
- [x] JPA
- [x] MCZ
- [ ] SLZ
- [x] BEL
- [x] POA
- [x] PNZ
- [x] GYN
- [x] VIX
- [x] CPV
- [x] BVB

https://twitter.com/jeffersonmj/status/582993495897440260

**Comment by mathma** [comment]
- [ ] FLN
- [ ] JOI
- [ ] AJU
- [ ] IGU

Correction: GRU is located in "Guarulhos, SP" not "São Paulo,SP"

**Comment by mathma** [comment]
"id": "fln",
    "code": "fln",
    "name": "Aeroporto Internacional de Florianópolis–Hercílio Luz",
    "nameEnglish": "Florianópolis–Hercílio Luz International Airport",
    "city": "Florianópolis",
    "city2": "Florianópolis",
    "city3": "Florianópolis",
    "state": "Santa Catarina",
    "stateShort": "SC",
    "country": "Brazil",
    "description": "Florianópolis Airport’s name honors former governor Hercílio Luz, but its airport code honors its home in **FL**oria**N**ópolis.",
    "imageCredit": "x",
    "imageCreditLink": "x"

**Comment by lynnandtonic** [comment]
Thank you, @mathma! :)
