### ISSUE TITLE
Blue Grass Airport LEX

### ISSUE THREAD

**Issue by tcrilly** [lynnandtonic/airport-codes#612]
Please add Blue Grass Airport (LEX)

Verbiage:
"Located in the Horse Capital of the World, Blue Grass Airport opened in 1946.  Its airport code honors its home in LEXington, Kentucky"

Thank you!

![tower horizontal](https://cloud.githubusercontent.com/assets/11788273/6985551/c47adc62-da02-11e4-88eb-399ac280fc77.jpg)

**Comment by lynnandtonic** [comment]
@tcrilly Thank you! Where did you get that photo? If from the web, can you provide a link?

**Comment by tcrilly** [comment]
The photo is from an internal photo database.  I believe the photo appears in several forms on our website: bluegrass airport.com<http://airport.com>.

Thanks for the assistance.

-Travis

Sent from my iPhone

On Apr 3, 2015, at 4:05 PM, Lynn Fisher <notifications@github.com<mailto:notifications@github.com>> wrote:


@tcrilly<https://github.com/tcrilly> Thank you! Where did you get that photo? If from the web, can you provide a link?

-

**Comment by lynnandtonic** [comment]
@tcrilly Oh, awesome! Thank you for the info and permission to use it. I'll get it added soon. :)

**Comment by lynnandtonic** [comment]
Thank you, @tcrilly! We'll push this live very soon. :)
