### ISSUE TITLE
+ LUN, NDL, LVI, JNB, DBR

### ISSUE THREAD

**Issue by ncrohn** [lynnandtonic/airport-codes#625]
https://twitter.com/KokulSiva/status/583192751828795392

- [x] LUN: http://en.wikipedia.org/wiki/Kenneth_Kaunda_International_Airport
- [x] NDL: http://en.wikipedia.org/wiki/N%27D%C3%A9l%C3%A9_Airport
- [x] LVI: http://en.wikipedia.org/wiki/Harry_Mwanga_Nkumbula_International_Airport
- [x] JNB: http://en.wikipedia.org/wiki/O._R._Tambo_International_Airport
- [ ] DBR: http://en.wikipedia.org/wiki/Durban_International_Airport

DBR is no longer listed as active for commercial service so not sure it should be added as it's IATA code isn't in use.

**Comment by lynnandtonic** [comment]
Skipping DBR since no longer designated.
