### ISSUE TITLE
+ AJF

### ISSUE THREAD

**Issue by ncrohn** [lynnandtonic/airport-codes#628]
https://twitter.com/ArabianSaluki/status/582749542858108928

- [x] DMM: http://en.wikipedia.org/wiki/King_Fahd_International_Airport
- [x] AHB: http://en.wikipedia.org/wiki/Abha_Regional_Airport
- [x] GIZ: http://en.wikipedia.org/wiki/Jizan_Regional_Airport
- [x] YNB: http://en.wikipedia.org/wiki/Yanbu_Airport
- [x] TIF: http://en.wikipedia.org/wiki/Ta%E2%80%99if_Regional_Airport
- [ ] AJF: http://en.wikipedia.org/wiki/Al-Jawf_Domestic_Airport
- [x] HOF: http://en.wikipedia.org/wiki/Al-Ahsa_International_Airport

**Comment by patilchetan** [comment]
@ncrohn @lynnandtonic:

Added DMM: https://github.com/lynnandtonic/airport-codes/pull/632

**Comment by lynnandtonic** [comment]
Having a hard time finding a photo for AJF. Here's content for now:

```
{
    "id": "ajf",
    "code": "ajf",
    "name": "Al-Jawf Domestic Airport",
    "city": "Sakakah",
    "city2": "Al-Jawf",
    "state": "Al Jawf Province",
    "country": "Saudi Arabia",
    "description": "Featuring a single runway, Al-Jawf Domestic Airport serves the city of Sakakah and gets its name and airport code from the city’s alternate name, *A*l-*J*aw*f*.",
    "imageCredit": "",
    "imageCreditLink": "https://www.flickr.com/photos//"
}
```
