### ISSUE TITLE
+ BNX, SJJ, OMO, TZL

### ISSUE THREAD

**Issue by farukgaric** [lynnandtonic/airport-codes#634]
Hi, I just want to suggest you these 4 airports from my country:

https://www.world-airport-codes.com/search/?apt=Bosnia&selected-airport=

- BNX - Banja Luka International Airport
- SJJ - Sarajevo International Airport
- OMO - Mostar International Airport
- TZL - Tuzla International Airport

Greetings from Bosnia!

**Comment by lynnandtonic** [comment]
- [ ] BNX
- [ ] SJJ
- [ ] OMO
- [ ] TZL

**Comment by lynnandtonic** [comment]
Thank you, @farukgaric! :+1:
