### ISSUE TITLE
CEK

### ISSUE THREAD

**Issue by mrked** [lynnandtonic/airport-codes#649]
Chelyabinsk International Airport is one of the Russian airport, located in the Ural region

**Comment by lynnandtonic** [comment]
Having difficulty find a photo. Here's content for now:

```
{
    "id": "cek",
    "code": "cek",
    "name": "Chelyabinsk Airport",
    "city": "Chelyabinsk",
    "country": "Russia",
    "description": "With a history dating back to the 1930s, Chelyabinsk Airport began serving international passengers in 1994. Its airport code comes from the city of *C*h*e*lyabins*k*.",
    "imageCredit": "",
    "imageCreditLink": ""
}
```

**Comment by mrked** [comment]
https://m.flickr.com/#/photos/98976474@N04/9567400160/in/search_QM_q_IS_баландино_AND_mt_IS_all_AND_w_IS_allMay be that one?Sent from Yahoo Mail for iPhoneAt 18 апр. 2015 г., 9:35:28, Lynn Fisher wrote:Having difficulty find a photo. Here's content for now:

{
    "id": "cek",
    "code": "cek",
    "name": "Chelyabinsk Airport",
    "city": "Chelyabinsk",
    "country": "Russia",
    "description": "With a history dating back to the 1930s, Chelyabinsk Airport began serving international passengers in 1994. Its airport code comes from the city of *C*h*e*lyabins*k*.",
    "imageCredit": "",
    "imageCreditLink": ""
}

**Comment by mrked** [comment]
http://pashkov.livejournal.com/photo/album/598/?mode=view&id=72920&page=23Photo of the old hall. Sent from Yahoo Mail for iPhoneAt 18 апр. 2015 г., 9:35:28, Lynn Fisher wrote:Having difficulty find a photo. Here's content for now:

{
    "id": "cek",
    "code": "cek",
    "name": "Chelyabinsk Airport",
    "city": "Chelyabinsk",
    "country": "Russia",
    "description": "With a history dating back to the 1930s, Chelyabinsk Airport began serving international passengers in 1994. Its airport code comes from the city of *C*h*e*lyabins*k*.",
    "imageCredit": "",
    "imageCreditLink": ""
}

**Comment by lynnandtonic** [comment]
Thank you, @mrked! :+1:
