### ISSUE TITLE
DSM

### ISSUE THREAD

**Issue by adischer** [lynnandtonic/airport-codes#654]
![dsm image](https://cloud.githubusercontent.com/assets/11810520/6998910/85f6bfd2-dbb6-11e4-84e1-7ec54ae3e2e4.jpg)

DSM
Des Moines International Airport
Des Moines, IA • USA
Iowa’s largest airport, the Des Moines International Airport’s code comes from its location in Des Moines.

**Comment by patilchetan** [comment]
@adischer, @lynnandtonic:

Added: https://github.com/lynnandtonic/airport-codes/pull/677
