### ISSUE TITLE
BHM Picture incorrect 

### ISSUE THREAD

**Issue by Soraito** [lynnandtonic/airport-codes#66]
Hi, just wanted to point out that the image used for the airport BHM is an image from the recently built air traffic control tower at Birmingham International Airport in the UK, instead of the Birmingham–Shuttlesworth International Airport in the US. I would also like to contribute BHX, Birmingham international airport in the UK to be added onto the list.
-Sora

**Comment by lynnandtonic** [comment]
@Soraito Thank you for pointing that out! I've never been to either airport so this is super helpful. :)

I'll get things straightened out soon.
