### ISSUE TITLE
SOB - Hévíz-Balaton airport

### ISSUE THREAD

**Issue by rcserti** [lynnandtonic/airport-codes#665]
located at Sármellék, Hungary.
http://en.wikipedia.org/wiki/H%C3%A9v%C3%ADz%E2%80%93Balaton_Airport

**Comment by lynnandtonic** [comment]
Doing a little research, but here's a photo that will work:

http://en.wikipedia.org/wiki/H%C3%A9v%C3%ADz%E2%80%93Balaton_Airport#/media/File:Peter_Stehlik_2011.08.29_001a_Flugplatz_Balaton_Flybalaton.jpg

**Comment by lynnandtonic** [comment]
Thank you, @rcserti!
