### ISSUE TITLE
Addition of SVD

### ISSUE THREAD

**Issue by luvi** [lynnandtonic/airport-codes#673]
SVD is the airport code for St.Vincent's Airport. St.Vincent is the largest of a chain of islands, and the entire country is known as St.Vincent and the Grenadines. Many of the Grenadines islands have their own airport, and subsequently their own airport code. St.Vincent's airport code stems from S from St, and V from Vincent... with the D standing for Diamond. The original airport location, where it comprised of a tiny airstrip which mainly accommodated cargo planes.

**Comment by chazzerguy** [comment]
https://en.wikipedia.org/wiki/E._T._Joshua_Airport

**Comment by lynnandtonic** [comment]
I couldn't find any sources that refer to the 'D' as Diamond, but I will keep looking. :)

Thank you, @luvi and @chazzerguy!

**Comment by luvi** [comment]
'The airport destination code for St. Vincent & the Grenadines is 'SVD' (St. Vincent Diamond); because the first airport in St. Vincent was located at Diamond, on the south east coast of St. Vincent.' http://www.discoversvg.com/index.php/fr/about-svg/did-you-know. Not St.Vincent Island, that is false :)
