### ISSUE TITLE
+ Iran airports

### ISSUE THREAD

**Issue by lynnandtonic** [lynnandtonic/airport-codes#705]
https://twitter.com/esggamin/status/587898088850911232

- [x] SYZ
- [x] TBZ
- [x] MHD
- [x] AWZ
- [x] KIH
- [x] BND
- [x] KER
- [x] KSH

**Comment by blacktrojan3921** [comment]
SYZ: Shiraz International Airport. I suspect that the S and Z represent the First and Last letters of ShiraZ, with the Y being a placeholder. http://untoldiran.com/image/shiraz/airport2.jpg

TBZ: Tabriz International Airport. TBZ are the letters found in TaBriZ . http://tabrizemodern.persiangig.com/chesm%20andaze%20tabriz/IMG_1940.JPG

MHD: Mashhad International Airport. MHD are the letters found in MashHaD . http://static.panoramio.com/photos/original/42926690.jpg

**Comment by lynnandtonic** [comment]
Thanks, @blacktrojan3921!
