### ISSUE TITLE
MGL

### ISSUE THREAD

**Issue by SQLThomas** [lynnandtonic/airport-codes#708]
This would be the airport in Mönchengladbach, Germany. 
Partly owned by Düsseldorf airport.
Sometimes called "Düsseldorf Mönchengladbach Airport".

IATA = MGL, ICAO = EDLN

http://en.wikipedia.org/wiki/D%C3%BCsseldorf_M%C3%B6nchengladbach_Airport

**Comment by lynnandtonic** [comment]
Thank you, @SQLThomas! :)
