### ISSUE TITLE
Please add AGU

### ISSUE THREAD

**Issue by fitojb** [lynnandtonic/airport-codes#709]
AGU is the code of the *Aeropuerto Internacional Lic. Jesús Terán Peredo*, or [Lic. Jesús Terán Peredo International Airport](https://en.wikipedia.org/wiki/Lic._Jes%C3%BAs_Ter%C3%A1n_Peredo_International_Airport), located in the city of Aguascalientes, Mexico.

Thanks!

**Comment by lynnandtonic** [comment]
Thank you, @fitojb! :+1:

**Comment by fitojb** [comment]
@lynnandtonic Thank *you* for the awesome work!
