### ISSUE TITLE
+ CTU

### ISSUE THREAD

**Issue by mythria** [lynnandtonic/airport-codes#718]
id = ctu
code = CTU
name = Chengdu Shuangliu International Airport
city = Chengdu
state = Sichuan
stateShort = 
country = China
description = Shuangliu Airport opened in 1938 as a supplementary airfield for WWII, after which several expansions were implemented making it now one of the busiest airports in China. The code of this airport derived from the city's former English name: ChengTU.

**Comment by lynnandtonic** [comment]
Thank you, @mythria! :)
