### ISSUE TITLE
+YQR 

### ISSUE THREAD

**Issue by blacktrojan3921** [lynnandtonic/airport-codes#726]
http://en.wikipedia.org/wiki/Regina_International_Airport

I suspect that the QR may come from the fact that Regina (where the R comes from) is Latin for Queen (where the Q comes from) 

In need of pics for this airport.

**Comment by blacktrojan3921** [comment]
I suspect that the QR may come from the fact that Regina (where the R comes from) is Latin for Queen  (where the Q comes from)

**Comment by lynnandtonic** [comment]
So interesting! Thank you, @blacktrojan3921! :+1:
