### ISSUE TITLE
+ LEJ

### ISSUE THREAD

**Issue by christianschulze** [lynnandtonic/airport-codes#728]
LE stands for Leipzig. Couldn't find out what the J stands for.
http://en.wikipedia.org/wiki/Leipzig/Halle_Airport

**Comment by lynnandtonic** [comment]
Thanks for the suggestion! I'm going to research the J from the code.

In the mean time, here's a photo that might work: https://flic.kr/p/6UFnqf

**Comment by christianschulze** [comment]
yeah, nice picture!

On 04.05.15 01:11, Lynn Fisher wrote:
>
> Thanks for the suggestion! I'm going to research the J from the code.
>
> In the mean time, here's a photo that might work: https://flic.kr/p/6UFnqf
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lynnandtonic/airport-codes/issues/728#issuecomment-98554830>.
>

-- 
Christian Schulze
Freelance Compositor & Developer

+49 162 6958971
chris@christian-schulze.eu

http://showreel.christian-schulze.eu/
http://www.christian-schulze.eu/

**Comment by teddylove85** [comment]
@lynnandtonic, @christianschulze I did a little research and this is what I found, LEJ stands for IATA code for Leipzig/Halle Airport, Leipzig, Germany(also Lashkar-e-Jhangvi and 17 more). The URL is http://www.allacronyms.com/LEJ/IATA_code_for_Leipzig%2FHalle_Airport,_Leipzig,_Germany

**Comment by teddylove85** [comment]
@lynnandtonic 

Leipzig Halle Airport

id = LEJ
code = LEJ
name = Leipzig Halle Airport
city = Schkeuditz
country = Germany

**Comment by lynnandtonic** [comment]
Thank you, @christianschulze and @teddylove85! :)

**Comment by christianschulze** [comment]
Awesome! You found out what the J stands for! :)
