### ISSUE TITLE
Please add Killeen-Fort Hood Regional - GRK

### ISSUE THREAD

**Issue by teddylove85** [lynnandtonic/airport-codes#734]
Killeen-Fort Hood Regional - GRK

id = GRK
code = GRK
name = Killeen-Fort Hood Regional
city = Killeen
state = Texas
stateShort = TX
country = USA

**Comment by lynnandtonic** [comment]
Thank you! :+1:

**Comment by teddylove85** [comment]
@lynnandtonic thank you for this webstie, this helps new travel agent figure out the different airports.

**Comment by lynnandtonic** [comment]
@teddylove85 That's really awesome to hear! Glad it's helped out. :)
