### ISSUE TITLE
Pressing Esc in detail view should close detail view

### ISSUE THREAD

**Issue by lynnandtonic** [lynnandtonic/airport-codes#736]
Per this comment: https://github.com/lynnandtonic/airport-codes/issues/23#issuecomment-87956074

**Comment by matiassingers** [comment]
:+1:

**Comment by matiassingers** [comment]
Awesome @ncrohn! :+1:

**Comment by lynnandtonic** [comment]
Thanks, @ncrohn! :raised_hands:
