### ISSUE TITLE
New PR?

### ISSUE THREAD

**Issue by alvarolmedo** [lynnandtonic/airport-codes#738]
Hi,

I would like contribute adding some airoports to this project.
I've created a new branch locally but I can push it in order to create the Pull Request (PR).... :(
Is it wrong this operation? What's the correct procedure?

**Comment by lynnandtonic** [comment]
Hi @alvarolmedo! To submit a PR, you'll first want to fork the repo. Once you fork, you'll want to clone your fork to your local, make your changes, push those changes to your fork, then submit a pull request back into this repo.

Here's some documentation on forking: https://help.github.com/articles/fork-a-repo/

Let me know if you run into any trouble. :)

**Comment by lynnandtonic** [comment]
@alvarolmedo I'm going to close this issue. Please email me at lynn@lynnandtonic.com if you have more questions. Thanks!
