### ISSUE TITLE
+ LEU: Andorra - la Seu d'Urgell airport

### ISSUE THREAD

**Issue by ErmengolPatalin** [lynnandtonic/airport-codes#748]
Andorra - la Seu d'Urgell airport
Aeroport Andorra - la Seu d'Urgell
City: La Seu d'Urgell, Catalonia, Spain

https://en.wikipedia.org/wiki/La_Seu_d%27Urgell_Airport

Photo CC BY-SA 2.0: https://commons.wikimedia.org/wiki/File:Pirineus_-_la_Seu_d%27Urgell_airport.jpg
![pirineus_-_la_seu_d urgell_airport](https://cloud.githubusercontent.com/assets/6871401/7684838/8df69078-fd89-11e4-81af-25a4f91510d8.jpg)

**Comment by lynnandtonic** [comment]
Thank you, @ErmengolPatalin! :+1:
