### ISSUE TITLE
+ VDE

### ISSUE THREAD

**Issue by churlos** [lynnandtonic/airport-codes#749]
Airport at the westernmost island within Canary Islands: El Hierro. Named after its main town: Valverde.

http://en.wikipedia.org/wiki/El_Hierro_Airport

![img_2934](https://cloud.githubusercontent.com/assets/12498704/7684019/46221e12-fd83-11e4-86d7-74a4a8ec73f9.JPG)
![img_2466](https://cloud.githubusercontent.com/assets/12498704/7684042/6386de02-fd83-11e4-8918-b0f8a1eb4e76.JPG)
![img_3186](https://cloud.githubusercontent.com/assets/12498704/7684056/7aab6bca-fd83-11e4-92be-691f86e82203.JPG)

**Comment by lynnandtonic** [comment]
Thank you, @churlos!
