### ISSUE TITLE
Make initial load faster, if possible

### ISSUE THREAD

**Issue by lynnandtonic** [lynnandtonic/airport-codes#773]
Not sure what would be best. Maybe images load after the boxes/text load? Maybe we need to host images elsewhere?

**Comment by lynnandtonic** [comment]
Looks like the CSS isn't minified in prod either, could you add that too?

**Comment by ncrohn** [comment]
I did some performance analysis, and it looks like it may be more than just typekit causing issues. Currently the javascript parsing and execution takes 1.5s which ends up delaying the load.

I'll need to investigate ways of speeding that up. I may just have the airports that will show in the viewport render first, then defer the rest of them to load after the page is rendered.

**Comment by lynnandtonic** [comment]
What is the JS parsing and executing at initial load?

**Comment by lynnandtonic** [comment]
How much is the JS doing during the initial load that could be done during a build step?

**Comment by ncrohn** [comment]
None of it can be moved off to a build step. It's the browser interpreting the JS, and then executing it. The main slow parts are the rendering of all 800+ airports. I should be able to make it a bit smarter so it only does what it needs to show the first section.

**Comment by lynnandtonic** [comment]
@ncrohn I still don't get how some of that couldn't be moved into a build step. Could we chat about this sometime this week?

**Comment by lynnandtonic** [comment]
Closing this for now.
