### ISSUE TITLE
PDL

### ISSUE THREAD

**Issue by VacuumPT** [lynnandtonic/airport-codes#777]
Name: João Paulo II Airport (in honour of the visit of the  Pope John Paul II to the Azores in 1991)
Location: Island of São Miguel, in the Portuguese archipelago of the Azores
Country: Portugal
Airport Code: comes from the name of the city where it's located - Ponta DeLgada (PDL).

**Comment by lynnandtonic** [comment]
Thank you, @VacuumPT! :)
