### ISSUE TITLE
HOR

### ISSUE THREAD

**Issue by VacuumPT** [lynnandtonic/airport-codes#780]
Name:  Aeroporto Internacional da Horta (Horta International Airport)
Info: inaugurated in 1971 and was remodeled and reinaugurated in 2001
Location: Island of Faial, in the Portuguese archipelago of the Azores
Country: Portugal
Airport Code: its airport code honors the city of HORta- HOR

**Comment by lynnandtonic** [comment]
Thank you, @VacuumPT!
