### ISSUE TITLE
GRW

### ISSUE THREAD

**Issue by VacuumPT** [lynnandtonic/airport-codes#782]
Name:  Aérodromo da Graciosa (Graciosa Airport)
Info: inaugurated in 1980
Location:  Santa Cruz da Graciosa - Graciosa Island, in the Portuguese archipelago of the Azores
Country: Portugal
Airport Code: its airport code honors the island of GRaciosa - GRW (a 'W’ as a filler letter)

**Comment by lynnandtonic** [comment]
Thank you!
