### ISSUE TITLE
SJZ

### ISSUE THREAD

**Issue by VacuumPT** [lynnandtonic/airport-codes#785]
Name: Aérodromo de São Jorge (São Jorge Airport)
Info: inaugurated in 1982
Location: Velas, São Jorge Island, in the Portuguese archipelago of the Azores
Country: Portugal
Airport Code: its airport code honors the island of São Jorge - SJZ (plus a ‘Z’ as a filler letter)

**Comment by lynnandtonic** [comment]
Thank you!
