### ISSUE TITLE
KFFA: First Flight

### ISSUE THREAD

**Issue by joeczab** [lynnandtonic/airport-codes#789]
Of course you have to include First Flight Airport on you listing.

KFFO (First  Flight Ohio), or Wright Patterson Air Force Base  is also an important landmark

**Comment by lynnandtonic** [comment]
Nice! We'll get this on the site soon.

http://en.wikipedia.org/wiki/First_Flight_Airport

**Comment by lynnandtonic** [comment]
Thank you, @joeczab! :+1:
