### ISSUE TITLE
DUD

### ISSUE THREAD

**Issue by BM6615** [lynnandtonic/airport-codes#808]
Built in 1962, DUneDin airport caters for more than 700,000 passengers a year.  International flights began in 1995 when the airport underwent a major extension.

The airport is well known for its Southern Man sculpture which sits outside the terminal building. Artist Sam Mahon welded together 50 bronze sections to create the sculpture, which was a gift from Speight’s Brewery. Stroking the horse’s nose is reputed to bring good luck.

**Comment by teddylove85** [comment]
Dunedin International Airport

id = DUD
code = DUD
name = Dunedin International Airport
city = Momona
city2 = Dunedin 9073
country = New Zealand

**Comment by lynnandtonic** [comment]
Thank you, @BM6615 and @teddylove85! :+1:
