### ISSUE TITLE
CHC

### ISSUE THREAD

**Issue by BM6615** [lynnandtonic/airport-codes#809]
Christchurch International Airport is located at Harewood, about 12 kilometres northwest of the centre of Christchurch. Christchurch International Airport was  opened on 18 May 1940 and became New Zealand's first international airport on 16 December 1950. It is named after CHristcChurch, the city is serves 

It is the second busiest airport in New Zealand by both annual passengers and aircraft movements. It is also the base for flights to Antartica.

**Comment by teddylove85** [comment]
Christchurch International Airport

id = CHC
code = CHC
name = Christchurch International Airport
city = Christchurch Airport
city2 =  Christchurch 8053 
country = New Zealand

**Comment by lynnandtonic** [comment]
Already on the site, thank you! http://airportcod.es/#airport/chc
