### ISSUE TITLE
NSN

### ISSUE THREAD

**Issue by BM6615** [lynnandtonic/airport-codes#810]
Nelson Airport is located in the suburb of Stoke. The airport is named after the city of NelSoN.

Construction of Nelson Airport commenced in 1937. The present terminal was opened in 1978.

 It is currently the sixth busiest airport in New Zealand by passengers and seventh by aircraft movements. Nelson airport is the home base of Air Nelson operating under the Air NZ Link banner, which operates a fleet of Bombardier Dash 8 Q300s on national air routes. Air New Zealand expanded its Nelson maintenance facility to handle sunsidary Mount Cook Airline's fleet of ATR 72-500/600 aircraft.

**Comment by teddylove85** [comment]
Nelson Airport

id = NSN
code = NSN
name = Nelson Airport
city = Nelson Airport
city2 = Nelson 7011
country = New Zealand

**Comment by lynnandtonic** [comment]
Thank you! <3
