### ISSUE TITLE
LXR - Luxor Airport, Luxor Egypt

### ISSUE THREAD

**Issue by curtandrus** [lynnandtonic/airport-codes#814]

**Comment by teddylove85** [comment]
Luxor International Airport

id = LXR
code = LXR
name = Luxor International Airport
city = Monshaat Al Amari
city2 = Luxor
city3 = Luxor Governorate
country = Egypt

**Comment by blacktrojan3921** [comment]
Photo: http://static.panoramio.com/photos/large/7272046.jpg

Meaning: Likely the name LuXoR.

**Comment by lynnandtonic** [comment]
Thanks, @curtandrus, @teddylove85, and @blacktrojan3921! That photo you included wasn't quite large enough, so I found a similar one from Flickr.

You are all awesome! <3
