### ISSUE TITLE
Kazakhstan Airports 

### ISSUE THREAD

**Issue by blacktrojan3921** [lynnandtonic/airport-codes#829]
SCO- Aktau Airport (Aktau, Kazakhstan) . Meaning: Likely in reference to it's former name ShevChenkO-Central
Image: https://upload.wikimedia.org/wikipedia/commons/d/d7/Aktau_Airport.jpg

AKX- Aktobe Airport (Aktobe, Kazakhstan) . Meaning: AKtobe , with the X likely filler. 
Image: http://static.panoramio.com/photos/large/61361063.jpg

KSN- Kostanay Airport (Kostanay, Kazakhstan) . Meaning: KoStaNay. 
Image: http://static.panoramio.com/photos/large/39517820.jpg

GUW- Atyrau Airport (Atyrau, Kazakhstan) . Meaning: Unknown, likely filler. 
https://upload.wikimedia.org/wikipedia/commons/7/72/Atyrau_Airport.JPG

CIT- Shymkent International Airport (Shymkent, Kazakhstan). Meaning: Unknown, likely filler. 
Image: https://irs2.4sqi.net/img/general/600x600/Q05GVPWDRT3NLRX3P4XVO1DJTPH31N2XRFA421IXXZE0EAJE.jpg 

KZO- Kyzylorda Airport (Kyzylorda, Kazakhstan) . Meaning: KyZylOrda . 
Image: https://mw2.google.com/mw-panoramio/photos/medium/61361030.jpg

URA- Oral Ak Zhol Airport (Oral/Uralsk), Kazakhstan). Meaning: Former name of airport and city, URAlsk. 
Image: https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Oral_Airport.JPG/600px-Oral_Airport.JPG

**Comment by lynnandtonic** [comment]
- [ ] SCO
- [ ] AKX
- [ ] KSN
- [ ] GUW
- [ ] CIT
- [ ] KZO
- [ ] URA

**Comment by lynnandtonic** [comment]
Thank you so much, @blacktrojan3921!
