### ISSUE TITLE
+ AYT

### ISSUE THREAD

**Issue by lynnandtonic** [lynnandtonic/airport-codes#830]
https://twitter.com/ady_shane/status/612016500631863296

**Comment by blacktrojan3921** [comment]
AYT: Antalya International Airport. 

Meaning: Likely from the name AnTalYa. 

Photo: https://upload.wikimedia.org/wikipedia/commons/3/38/Antalya_Airport_-_International_Terminal_2.JPG

**Comment by teddylove85** [comment]
id = AYT
code = AYT
name = Antalya International Airport
city = Dış Hatlar Terminali
city 2 = 7230 Antalya
country = Turkey

**Comment by lynnandtonic** [comment]
:+1:
