### ISSUE TITLE
Fairoaks airport

### ISSUE THREAD

**Issue by cinders47** [lynnandtonic/airport-codes#833]
Fairoaks Airport
Chertsey Road
Chobham
Woking GU24 8HU
UK
Tel +44 1276 857272
Code FRK
Altitude 24m

**Comment by lynnandtonic** [comment]
Fairoaks Airport unfortunately does not have an IATA code (it does have an ICAO code, though). FRK actually designates Fregate Island Airport.

Because it doesn't have an IATA code we won't be adding it to the site. Thank you so much for the suggestion, though. We really appreciate it!

**Comment by cinders47** [comment]
Hi Lynn,

Thanks for the reply.

I'll keep trying!

David
