### ISSUE TITLE
+ SIR

### ISSUE THREAD

**Issue by lynnandtonic** [lynnandtonic/airport-codes#848]
https://twitter.com/andypkopp/status/635425314479411200

**Comment by lynnandtonic** [comment]
https://flic.kr/p/6YcHyL

**Comment by Mokas-Uncle** [comment]
SIR stands for Sion/Rhone which is the the name of the river next to the airport and also of the valley in which the airport is located.

**Comment by lynnandtonic** [comment]
Thank you!
