### ISSUE TITLE
+ SJD

### ISSUE THREAD

**Issue by totoros** [lynnandtonic/airport-codes#854]
Los Cabos International Airport 

https://www.flickr.com/photos/ricardoviana/12883248465/in/photolist-kCs1Vx-dXdX3D-8QGBVK-p2yCft-fjVS2x-a5yxMF-95hjco-95eeoD-95eexT-95eeqK-95hjrQ-pj3Kd2-8QGCrT-cimyQA-cimyk5-cimyGs-jB2Hh-daojCx-hxGfCQ-hxG1nz-hxGNAL-hxGNsE-jB2Pi-jB2Jh-jB2L9-cim7tw-wHrY6s-wLgm3H-vNKhPS-hxGfvq-oYCPy1-hxG1Np-jB2MH-uPnNwo-wt9F53-wtgZAZ-jB2QB-5rQsrA-5rQsnm-5rQsgm-5rQfy5-5rKVCX-5rQsjA-5rL8ji-cim7by-cimxW9-6Dsaz6-r6eQii-v8pFdi-6DsZr2

https://en.wikipedia.org/wiki/Los_Cabos_International_Airport

**Comment by lynnandtonic** [comment]
Thank you, @totoros! The photo you linked to is copyrighted so I picked a different one. :)
