### ISSUE TITLE
LBC 

### ISSUE THREAD

**Issue by Mokas-Uncle** [lynnandtonic/airport-codes#860]
Hi, 

great site; I enjoy it.

Here is an additional a norther German airport: LBC stands for Lübeck.

Often referred to as Hamburg-Lübeck, because this city of 250,000 is so close to Hamburg. Any reference to Hamburg drives the mayor of Lübeck mad. This doesn't really help much to save the airport from bankruptcy.
![lbc](https://cloud.githubusercontent.com/assets/15101875/10448411/00d38c82-718d-11e5-89f4-b62edcf5e5bd.jpg)
https://en.wikipedia.org/wiki/Lübeck_Airport

**Comment by lynnandtonic** [comment]
Well, 2.5 years later... Sorry for the intense delay on this one. Thank you @Mokas-Uncle!
