### ISSUE TITLE
RLG

### ISSUE THREAD

**Issue by Mokas-Uncle** [lynnandtonic/airport-codes#861]
another northern German airport is RLG - which stands for Rostock Laage.

Rostock, a city of 200,000, is located on the Baltic shore and is the economic centre of the state of Mecklenburg-Westpommerania. Does it need an airport? Why not.

https://en.wikipedia.org/wiki/Rostock–Laage_Airport
![rlg](https://cloud.githubusercontent.com/assets/15101875/10448531/bcb447ca-718d-11e5-82f3-aa980fa99fd7.jpg)

**Comment by lynnandtonic** [comment]
Thank you, @Mokas-Uncle! :+1:
