### ISSUE TITLE
GOA

### ISSUE THREAD

**Issue by Mokas-Uncle** [lynnandtonic/airport-codes#862]
A big cruise port needs an airport - and probably a better one than Genova (GOA) offers

https://en.wikipedia.org/wiki/Genoa_Cristoforo_Colombo_Airport
![goa](https://cloud.githubusercontent.com/assets/15101875/10453310/5c73af68-71ab-11e5-9357-73148c769249.jpg)
![goa1](https://cloud.githubusercontent.com/assets/15101875/10453331/8bb2dfba-71ab-11e5-8d4d-d8934748c52f.jpg)

**Comment by lynnandtonic** [comment]
Thank you!
