### ISSUE TITLE
YSB

### ISSUE THREAD

**Issue by Mokas-Uncle** [lynnandtonic/airport-codes#863]
YSB is one of the less mysterious Canadian airport codes as the SB obviously stands for Sudbury, ON.

https://en.wikipedia.org/wiki/Sudbury_Airport
![ysb](https://cloud.githubusercontent.com/assets/15101875/10476155/9bf6e39e-724b-11e5-9002-ac7127ff9891.jpg)

**Comment by lynnandtonic** [comment]
Thank you! :dancer:
