### ISSUE TITLE
INN

### ISSUE THREAD

**Issue by Mokas-Uncle** [lynnandtonic/airport-codes#865]
INNsbruck airport serves Western Austria and the city of Innsbruck and is very popular in winter for all the skiers going to St. Anton in the Tyrol region.

https://en.wikipedia.org/wiki/Innsbruck_Airport
![inn](https://cloud.githubusercontent.com/assets/15101875/10476633/d8e59a3a-724f-11e5-8b96-aac27c20e4f7.jpg)

**Comment by lynnandtonic** [comment]
Thank you! <3
