### ISSUE TITLE
GRZ

### ISSUE THREAD

**Issue by Mokas-Uncle** [lynnandtonic/airport-codes#866]
Graz is a nice little city in the beautiful region of Styria in Southern Austria and is served by the nice little airport GRZ.

https://en.wikipedia.org/wiki/Graz_Airport
![grz](https://cloud.githubusercontent.com/assets/15101875/10477533/4137ec26-7257-11e5-8383-89cbe5f7a222.jpg)

**Comment by lynnandtonic** [comment]
@Mokas-Uncle Where are you getting these images from? Are they your own work?

**Comment by lynnandtonic** [comment]
Thank you!

**Comment by Mokas-Uncle** [comment]
I am not a good photographer, so these are not my own photos. Most of them are from wikipedia or directly from the airport website.
