### ISSUE TITLE
KUO

### ISSUE THREAD

**Issue by Mokas-Uncle** [lynnandtonic/airport-codes#867]
Most of Finlands population lives in the Helsinki area and the other airports are certainly not huge. Kuopio is a city of just over 100,000 located in the Saimaa lake district which is served by KUO airport.

https://en.wikipedia.org/wiki/Kuopio_Airport
![kuo](https://cloud.githubusercontent.com/assets/15101875/10477645/1547e598-7258-11e5-9e5c-de1fd07d5a0c.jpg)

**Comment by lynnandtonic** [comment]
Thank you!
