### ISSUE TITLE
VRN

### ISSUE THREAD

**Issue by Mokas-Uncle** [lynnandtonic/airport-codes#868]
The city of Romeo and Juliet is just wonderful - unless you arrive by plane. The beauty of Verona (VRN) is concealed inside and the airport is located in a boring industrial landscape.

https://en.wikipedia.org/wiki/Verona_Villafranca_Airport

![vrn](https://cloud.githubusercontent.com/assets/15101875/10477730/e57c29c2-7258-11e5-90cd-a2364561c3fd.jpg)

**Comment by lynnandtonic** [comment]
Thank you!
