### ISSUE TITLE
BQH

### ISSUE THREAD

**Issue by Mokas-Uncle** [lynnandtonic/airport-codes#871]
For those in a hurry and all the people who hate long lines at security Biggin Hill (BQH) is a very convenient alternative to the 5 very crowded airports of greater London - provided you have a private plane at your disposal. 

https://en.wikipedia.org/wiki/London_Biggin_Hill_Airport
![bqh](https://cloud.githubusercontent.com/assets/15101875/10478139/a328d5fe-725b-11e5-91c0-8a1f58be1bde.jpg)

**Comment by lynnandtonic** [comment]
Thank you, @Mokas-Uncle! :+1:
