### ISSUE TITLE
PAS

### ISSUE THREAD

**Issue by Mokas-Uncle** [lynnandtonic/airport-codes#872]
The Greek island of Paros (PAS) has a small airstrip with a wonderful antique but fully sufficient airport terminal to serve the ca. 25,000 passengers p.a.

https://en.wikipedia.org/wiki/Paros_National_Airport
![pas](https://cloud.githubusercontent.com/assets/15101875/10478241/695a9e92-725c-11e5-8597-917def3ebfae.jpg)

**Comment by lynnandtonic** [comment]
```
{
    "id": "pas",
    "name": "Paros National Airport",
    "city": "Paros",
    "country": "Greece",
    "description": "Opened in 1982, *Pa*ro*s* National is often called Panteleou Paros Airport after Nikolas Panteleou who provided the land where the airport now sits.",
    "imageCredit": "",
    "imageCreditLink": ""
}
```

**Comment by lynnandtonic** [comment]
@Mokas-Uncle Where is that photo from? Do you have a high-res one you could email me?

**Comment by Mokas-Uncle** [comment]
Hi Lynn,

I picked the photo to illustrate this nice little airport terminal from a flickr site
Paros Airport 2 | Flickr - Photo Sharing! <https://www.flickr.com/photos/johndoray/1045833045/>

Unfortunately I neither own the copyrights nor do I have a high res copy.

Kind Regards
Lars

**Comment by lynnandtonic** [comment]
Ah ok, thank you Lars! Unfortunately the photo is copyrighted, so I'll look around for a photo we can use.
