### ISSUE TITLE
TRS

### ISSUE THREAD

**Issue by Mokas-Uncle** [lynnandtonic/airport-codes#873]
Trieste (TRS) is located on the Italian/Slovenian border where the alps descend into the Adriatic Sea. This location comes with a lot of gusty winds which makes approaches turbulent at times.

https://en.wikipedia.org/wiki/Trieste_–_Friuli_Venezia_Giulia_Airport
![trs](https://cloud.githubusercontent.com/assets/15101875/10478344/26cf14da-725d-11e5-93c7-f032417d0c11.jpg)

**Comment by lynnandtonic** [comment]
Added already, will be on the site soon. Thank you!
