### ISSUE TITLE
+TSA

### ISSUE THREAD

**Issue by chi227** [lynnandtonic/airport-codes#877]
{
    "id": "TSA",
    "name": "Taipei Songshan Airport",
    "city": "Taipei",
    "city2": "Taipei City",
    "country": "Taiwan",
    "description": "The city airport in the capital city of Taiwan. It's airport code honors the airport name, *T*aipei *S8ongshan *A*irport",
![taipei_international_airport_pickup](https://cloud.githubusercontent.com/assets/15961744/11321203/dc9d498e-90ef-11e5-8295-e370cd35bbba.jpg)

}

**Comment by lynnandtonic** [comment]
Thank you, @chi227! :)
