### ISSUE TITLE
Punta del Este, Uruguay

### ISSUE THREAD

**Issue by nacheinuru** [lynnandtonic/airport-codes#880]
PDP Airport is Uruguay´s second airport in size, and has scheduled commercial flights to AEP (Aerolíneas Argentinas) and GRU (Tam). It was designed by a well know Uruguayan architect, Carlos Ott, who worked on the Bastille Opera project in Paris
The name stands for
Punta
Del
Piriápolis - the Municipality where the airport is located
![pdpairport](https://cloud.githubusercontent.com/assets/16168757/11609447/998763c0-9b65-11e5-8bc4-c5cd9d4c9aa6.jpg)

**Comment by lynnandtonic** [comment]
```
{
    "id": "pdp",
    "name": "Aeropuerto Internacional Capitán de Corbeta Carlos A. Curbelo",
    "nameEnglish": "Capitán de Corbeta Carlos A. Curbelo International Airport",
    "city": "Punta del Este",
    "city2": "Piriápolis",
    "country": "Uruguay",
    "description": "Commonly called Laguna del Sauce Airport, Capitán de Corbeta Carlos A. Curbelo International gets its three-letter code from the cities it serves: *P*unta *d*el Este and *P*iriápolis.",
    "imageCredit": "",
    "imageCreditLink": ""
}
```
