### ISSUE TITLE
+ LRH

### ISSUE THREAD

**Issue by andre4s** [lynnandtonic/airport-codes#882]
La Rochelle – Île de Ré
===
*La Rochelle, France*

- [Wikipedia](https://en.wikipedia.org/wiki/La_Rochelle_–_Île_de_Ré_Airport) – the photo's quite old though
- [GCMap](http://www.gcmap.com/cgi-bin/gc2q?Q=lrh&QCa=Airport+Info&QD=S)

**Comment by lynnandtonic** [comment]
Thank you, @andre4s! :+1:
