### ISSUE TITLE
+ AKT

### ISSUE THREAD

**Issue by atdr** [lynnandtonic/airport-codes#883]
# RAF Akrotiri

_Akrotiri, Cyprus_

Launch base for many British aircraft involved in Middle East operations, [including current airstrikes in Syria](http://www.bbc.co.uk/news/uk-35016533).
- [GCMap](http://www.gcmap.com/cgi-bin/gc2q?Q=akt&QCa=Airport+Info&QD=A)
- [Wikipedia](https://en.wikipedia.org/wiki/RAF_Akrotiri)

**Comment by lynnandtonic** [comment]
```
{
    "id": "akt",
    "name": "Royal Air Force Akrotiri",
    "city": "Akrotiri",
    "country": "Cyprus",
    "description": "Due to its proximity to the Middle East, RAF *Ak*ro*t*iri often serves as a launch base for British aircrafts into the region.",
    "imageCredit": "",
    "imageCreditLink": ""
}
```
