### ISSUE TITLE
+ NIC

### ISSUE THREAD

**Issue by andre4s** [lynnandtonic/airport-codes#884]
Nicosia (Lefkosia – Λευκωσία) International Airport
===
*Nicosia, Cyprus*

Closed since the [Turkish invasion of Cyprus](https://en.wikipedia.org/wiki/Turkish_invasion_of_Cyprus), it recently [hosted talks between the two sides](http://www.sigmalive.com/en/news/politics/137767).

- [GCMap](http://www.gcmap.com/airport/NIC.OLD)
- [Wikipedia](https://en.wikipedia.org/wiki/Nicosia_International_Airport)

**Comment by lynnandtonic** [comment]
A unique airport for sure! Thank you, @andre4s!
