### ISSUE TITLE
MDQ

### ISSUE THREAD

**Issue by ferlapo** [lynnandtonic/airport-codes#890]
This name is because the name MDP (For the name Mar Del Plata) was taken by another airport. So, they changhed the P for a Q (the next letter)
![mdq_hoy_21](https://cloud.githubusercontent.com/assets/16888799/12568096/05cc1abc-c3a2-11e5-9860-75fe6eadcfa8.jpg)

**Comment by lynnandtonic** [comment]
@ferlapo Did you take that photo? If so, do you have a high-res version you could email me? lynn@lynnandtonic.com

**Comment by lynnandtonic** [comment]
```
{
    "id": "mdq",
    "name": "Aeropuerto Internacional de Mar del Plata “Ástor Piazzolla”",
    "nameEnglish": "Astor Piazzolla International Airport",
    "city": "Mar del Plata",
    "country": "Argentina",
    "description": "",
    "imageCredit": "",
    "imageCreditLink": "Named after an Argentine musician, Astor Piazzolla International is located in *M*ar *d*el Plata. With MDP already taken, its code uses the letter ‘*Q*’ in place of the ‘P’."
}
```
