### ISSUE TITLE
+ CBQ

### ISSUE THREAD

**Issue by atdr** [lynnandtonic/airport-codes#891]
# Calabar (Margaret Expo International) Airport, Nigeria

DNCA / CBQ
- [GCMap](http://www.gcmap.com/airport/CBQ)
- [Wikipedia](https://en.wikipedia.org/wiki/Margaret_Ekpo_International_Airport)

**Comment by lynnandtonic** [comment]
Photo: https://en.wikipedia.org/wiki/Margaret_Ekpo_International_Airport#/media/File:Calabar_International_Airport,_Cross_river.jpg

**Comment by lynnandtonic** [comment]
Closed with #1300
