### ISSUE TITLE
+ ANG

### ISSUE THREAD

**Issue by andre4s** [lynnandtonic/airport-codes#893]
Angoulême – Cognac International Airport
===
Poitou-Charentes, France
*LFBU / ANG*

- [GCMap](http://www.gcmap.com/airport/ANG)
- [Wikipedia](https://en.wikipedia.org/wiki/Angoulême_–_Cognac_International_Airport)

**Comment by lynnandtonic** [comment]
Photo: https://commons.wikimedia.org/wiki/File:Angou_airport5.JPG

**Comment by lynnandtonic** [comment]
Thank you, @andre4s!
