### ISSUE TITLE
+VVI 

### ISSUE THREAD

**Issue by thaezb** [lynnandtonic/airport-codes#905]
https://es.wikipedia.org/wiki/Aeropuerto_Internacional_Viru_Viru

The correct name derives from the word Birubiru , which refers to a now archaic dry river , which cuts the pampa 13 kilometers north of the capital city. In the central part of the pampa the airport is with the spelling Viru Viru formed by two words. Vee ( v ) it is not pronounced both regional native languages ​​as in popular speech of Santa Cruz , who owns the airport.

**Comment by lynnandtonic** [comment]
```
{
    "id": "vvi",
    "name": "Aeropuerto Internacional Viru Viru",
    "nameEnglish": "Viru Viru International Airport",
    "city": "Santa Cruz de la Sierra",
    "country": "Bolivia",
    "description": "*V*iru *V*iru *I*nternational opened in 1983 and replaced El Trompillo Airport. Its name is derived from the word “Birubiru”, which refers to a now dry nearby river.",
    "imageCredit": "",
    "imageCreditLink": ""
}
```

**Comment by lynnandtonic** [comment]
Well, it took me forever to get to this. Thank you @thaezb for your suggestion! 👍
