### ISSUE TITLE
+ SZX

### ISSUE THREAD

**Issue by lynnandtonic** [lynnandtonic/airport-codes#912]

**Comment by lynnandtonic** [comment]
Photos:
https://flic.kr/p/nhdUMr
https://flic.kr/p/iryton

**Comment by blacktrojan3921** [comment]
The first two letters refer to the name of the city 'ShenZen' and the X may be a filler letter.

**Comment by lynnandtonic** [comment]
https://twitter.com/niteshkchouhan/status/1088056833850261510

**Comment by lynnandtonic** [comment]
https://twitter.com/gaberadical/status/1113522607427600384
