### ISSUE TITLE
JAX airport did not add the 'X' for the standard reason

### ISSUE THREAD

**Issue by quintincarlson** [lynnandtonic/airport-codes#942]
Copy should be changed:

Jacksonville International Airport gets its code from the shortened phrase "Jax." Residents of Jacksonville, FL use this three letter acronym describe the city and append to the name of local services and businesses.

**Comment by lynnandtonic** [comment]
@quintincarlson Ah, makes sense! I'll get that changed soon. Thank you!

**Comment by quintincarlson** [comment]
No problem. I love your site!

**Comment by lynnandtonic** [comment]
Thank you, @quintincarlson! :)
